<?
	if(isset($vars['curr_cat']['text'])&&$vars['curr_cat']['text']!="")echo'<div class="cat_desc">'.htmlspecialchars_decode($vars['curr_cat']['text']).'</div>';
	if(isset($vars['discount_text'])&&$vars['discount_text']['text']!="")echo'<div class="cat_desc">'.htmlspecialchars_decode($vars['discount_text']['text']).'</div>';
	if(isset($vars['product'])&&count($vars['product'])!=0)
	{
		
		?>
        <div id="sort_block">
        <form action="" id="sort_block" method="post">
        	<label for="selectPrductSort">Сортировать по: </label>
            <select id="selectPrductSort" name="sort" onchange="submit();">
                <option selected="selected" value="">Последние добавления</option>
                <option value="price:asc"<? if($_SESSION['sort']=="price asc")echo' selected="selected"';?>>по цене, сначала дешевые</option>
                <option value="price:desc"<? if($_SESSION['sort']=="price desc")echo' selected="selected"';?>>по цене, сначала дорогие</option>
                <option value="name:asc"<? if($_SESSION['sort']=="name asc")echo' selected="selected"';?>>по наименованию: А-Я</option>
                <option value="name:desc"<? if($_SESSION['sort']=="name desc")echo' selected="selected"';?>>по наименованию: Я-А</option>
            </select>
		</form>
        </div>
        <?
		echo'<div>';
		if(isset($vars['brend'])&&count($vars['brend'])!=0)
		{
			echo"<span>Бренд:</span> ";
			if(isset($vars['brend_id']))echo"<a href='".$this->getUrl2("brend")."'>Все</a>";
			else echo"<span style='font-weight:100;'>Все</span>";
			foreach($vars['brend'] as $row)
			{
				echo" | ";
				if(isset($vars['brend_id'])&&$vars['brend_id']==$row['url'])echo"<span style='font-weight:100;'>{$row['name']}</span>";
				else echo"<a href='".$this->getUrl("brend", $row['url'])."'>{$row['name']}</a>";
				
			}
		}
		echo'</div><br class="clear" />';
		$i=1;
		foreach($vars['product'] as $row)
		{
			include "product.phtml";
			$i++;
		}
		echo'<div class="clear"></div>';
		echo $vars['paging'];
	}
	else echo'<p class="warning">Каталог пуст</p>';
?>