<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?php echo $vars['meta']['title'];?></title>
		<meta name="keywords" content="<?php echo $vars['meta']['keywords']; ?>" />
		<meta name="description" content="<?php echo $vars['meta']['description']; ?>" />
		<meta name="copyright" content="" />
		<meta name="Author-Corporate" content="" />
		<meta name="Publisher-Email" content="" />
        <link rel="stylesheet" type="text/css" href="/tpl/styles/fancy.css" />
        <link href="/tpl/styles/validationEngine.jquery.css" rel="stylesheet" type="text/css" />
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
        <link href="/tpl/styles/style.css" rel="stylesheet" type="text/css" media="all" />
        <link href="/tpl/styles/sticker.css" rel="stylesheet" type="text/css" media="all" />
        <link rel="stylesheet" href="/tpl/styles/jquery.sb.css" type="text/css" />
        <!--[if lte IE 7]>
            <link href="<?php echo $this->LoadResource('styles', 'style_ie.css'); ?>" rel="stylesheet" type="text/css" />
        <![endif]-->
		<script type="text/javascript" src="/tpl/scripts/jquery-1.4.2.min.js"></script>
        <script src="/tpl/scripts/jquery.validationEngine-ru.js" type="text/javascript"></script>
        <script src="/tpl/scripts/jquery.validationEngine.js" type="text/javascript"></script>
        <script type="text/javascript" src="/tpl/scripts/cart.js"></script>
        <script type="text/javascript" src="/tpl/scripts/print.js"></script>
        <script type="text/javascript" src="/tpl/scripts/jquery.stickr.min.js"></script>
        <script type="text/javascript" src="/tpl/scripts/jquery.fancybox-1.3.4.js"></script>
        <script type="text/javascript" src="/tpl/scripts/jquery.fancybox-1.3.4.pack.js"></script>
        <script type="text/javascript" src="/tpl/scripts/jquery.sb.min.js"></script>
        <script type="text/javascript" src="/tpl/scripts/jquery.scrollTo-1.4.2.js"></script>
        <script type="text/javascript">
			$(document).ready(function(){
				$("a[rel=lightbox]").fancybox({
                        'transitionIn'		: 'none',
                        'transitionOut'		: 'none',
                        'titlePosition' 	: 'over',
                        'titleFormat'		: function(title, currentArray, currentIndex, currentOpts) {
                            return '<span id="fancybox-title-over">Image ' + (currentIndex + 1) + ' / ' + currentArray.length + (title.length ? ' &nbsp; ' + title : '') + '</span>';
                        }
            	});
				$("#formID").validationEngine();});
	  
	</script>
</head>
<body>
<div id="head">
    <div class="container">
    <?php
	/*$date=mktime(03+9, date("i"), 0, date("m"), date("d"), date("Y"));
	$date=getdate($date);
	echo $date['mday']." - ".$date['mon']." - ".$date['year'];/*/
		include"main_menu.phtml";
		
		include"auth_block.phtml";
	?>
        <div id="logo"><a href="/"><img src="/tpl/images/logo.png" alt="" /></a></div>
    </div>  
    <? $style_index='';if($vars['topic']=="index"){include"start_img.phtml";$style_index=' style="margin-top:100px;"';}?>
</div>   
   
<div class="container" id="light">
    <div id="left_col"<?=$style_index?>>
    	<?php 
			include"left_menu.phtml";
			/*echo'<div class="title_green"><div>Онлайн консультант</div></div>
					 <div class="left_block"></div>';	*/

			if(count($vars['news'])!=0&&$vars['topic']=="index")
			{
				echo'<div class="left_title">Новости</div>
					 <div class="left_menu"><div class="bot_left"><ul id="news_left">';
				$i=0;
				foreach($vars['news'] as $row)
				{
					if($i==0)$back='style="background-image:none;"';
					else $back='';
					echo'<li><a href="/news/'.$row['url'].'" title="'.$row['name'].'" '.$back.'>'.$row['name'].'</a><span>'.$row['m_text'].'</span><br /><a href="/news/'.$row['url'].'" class="more_m">Читать далее ></a></li>';	
					$i++;
				}
				echo'<li><a href="/news/all" class="all_news">Все новости</a></li></ul></div></div>';
			}
	?>
    </div>
    <div id="right_col"<?=$style_index?>>
		<?php 
			if($vars['breadcrumb']!="")echo'<div class="breadcrumb">'.$vars['breadcrumb'].'</div>';
			echo $vars['message_auth'];
			echo $vars['content'];
		?>
    </div>
    <div class="clear"></div>
</div>
<div id="footer">
	<div class="container">
        <div style="width:287px; float:left; padding:8px 0 0 15px;">
			<?=htmlspecialchars_decode($vars['contacts']['text'])?>
        </div>
        <div style="width:650px; float:left; text-align:right;">
			<?=htmlspecialchars_decode($vars['soc']['text'])?>
			<?=$vars['translate']['copyright']?><br />
            <a href="http://skylogic.com.ua" target="_blank"><?=$vars['translate']['skylogic']?></a>
        </div>
        <div class="clear"></div>
    </div> 
</div>

<script type="text/javascript">
$(document).ready(function(){
	$('input[name=search]').click(function(){if($('input[name=search]').val()=="Поиск...")$('input[name=search]').val('');});
	$('input[name=name_left]').click(function(){if($('input[name=name_left]').val()=="Ваше имя")$('input[name=name_left]').val('');});
	$('input[name=email_left]').click(function(){if($('input[name=email_left]').val()=="Ваш E-mail")$('input[name=email_left]').val('');});
	$('textarea[name=text_left]').click(function(){if($('textarea[name=text_left]').val()=="Ваше сообщение")$('textarea[name=text_left]').val('');});
	$('input[name=captcha]').click(function(){if($('input[name=captcha]').val()=="Введите код")$('input[name=captcha]').val('');});
	$('#enter').click(function(){if($('#auth_block').css('display')=='block')$('#auth_block').css('display', 'none');else $('#auth_block').css('display', 'block');});
});

$(document).ready(function(){$('.buy').live('click',function(){
$.stickr({note:'Товар добавлен!',className:'next',position:{right:0,bottom:0},time:1000,speed:300});
var id=$(this).attr('id');
var cnt=$('#cnt'+id).val();//alert(cnt);
var dataString = 'id='+id+'&cnt='+cnt;
$.ajax({type: "POST",url: "/incmodules/in_cart.php",data: dataString,cache: false,success: function(html){bascket('<?=session_id()?>');}});});
bascket('<?=session_id()?>');
});
$(document).ready(function() {
		  $("[name=brends], [name=onpage], [name=sort], [name=pay]").sb();
		});
</script>
<?php
	if(isset($vars['google']))echo"<script type=\"text/javascript\">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '".$vars['google']."']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>";
?>
<div class="clear"></div>
</body>
</html>