<div class="cm-notification-container"></div>
<?=$vars['message']?>
<div class="cm-tabs-content">
    <div class="clear mainbox-title-container">
        <h1 class="mainbox-title">Редактирование:&nbsp;<?=$vars['edit']['name']?></h1>
    </div>
    <div class="extra-tools">
        
        <a class="tool-link" href="/admin/<?=$vars['action']?>/add">Добавить</a>
        <a class="tool-link cm-confirm" href="/admin/<?=$vars['action']?>/delete/<?=$vars['edit']['id']?>">Удалить</a>
        <div class="float-right preview-link">
            <a href="/news/<?=$vars['edit']['url']?>" title="<?=$vars['edit']['url']?>" class="tool-link" target="_blank">Предпросмотр</a>
        </div>
    </div>
    <div class="mainbox-body">
    	<div class="tabs cm-j-tabs cm-track">
            <ul>
                <li id="basic" class="cm-js cm-active"><a >Общее</a></li>
                <li id="metadata" class="cm-js"><a >Фото</a></li>
            </ul>
        </div>
        
        <form class="cm-form-highlight cm-check-changes" name="page_update_form" method="post" action="" enctype="multipart/form-data">
            <input type="hidden" value="<?=$vars['edit']['id']?>" name="id" />
            <div id="content_basic" class="cm-tabs">
                <fieldset>
                    <h2 class="subheader"> Информация </h2>
                    <div class="form-field">
                        <label class="cm-required" for="page">Подпись:</label>
                        <input type="text" class="input-text-large main-input" value="<?=$vars['edit']['name']?>" size="55" name="name" />
                    </div>
                    <div class="form-field">
                        <label for="page">URL:</label>
                        <input type="text" class="input-text-large main-input" value="<?=$vars['edit']['url']?>" size="55" name="url" />
                    </div>
                    <div class="form-field">
                        <label class="cm-required">Статус:</label>
                        <div class="select-field">
                            <input type="radio" class="radio" value="1" id="page_data_0_a" name="active" <? if($vars['edit']['active']==1)echo' checked="checked"';?>>
                            <label for="page_data_0_a">Вкл.</label>
                            <input type="radio" class="radio" value="0" id="page_data_0_d" name="active" <? if($vars['edit']['active']==0)echo' checked="checked"';?>>
                            <label for="page_data_0_d">Выкл.</label>
                        </div>
                    </div>
                </fieldset>
			</div>
             <!--metdata start-->
            <div id="content_metadata" class="cm-tabs hidden">
                <fieldset>
                    <h2 class="subheader">Фото</h2>
                    <div class="form-field" style="padding:0;">
                        <?php
                        $vars['path']="files/slider/";
                        $vars['image_id']=$vars['edit']['id'];
                        include $_SERVER['DOCUMENT_ROOT']."/tpl/admin/upload_img.phtml";
                        ?>
                    </div>
                </fieldset>
            </div>
            <div class="buttons-container cm-toggle-button buttons-bg">
                <div class="cm-buttons-floating hidden" style="display: block;">
                    <div class="cm-buttons-placeholder">
                        <span class="submit-button cm-button-main">
                            <input type="submit" value="Сохранить" name="update" />
                        </span>&nbsp;
                        <span class="submit-button cm-button-main cm-save-and-close">
                            <input type="submit" value="Сохранить и закрыть" name="update_close" class="cm-save-and-close" />
                        </span> &nbsp;или&nbsp;&nbsp;
                        <a class="underlined tool-link" href="/admin/<?=$vars['action']?>">Отменить</a>
                    </div>
                </div>
            </div>
            <input type="hidden" value="<?=$vars['action']?>" id="action" />
        </form>
    </div>
</div>