<div class="items-container multi-level">
<table width="100%" cellspacing="0" cellpadding="0" border="0" class="table table-fixed hidden-inputs tb_sort">
	<tr class="noDrop">
		<th width="3%" class="center"><input type="checkbox" class="check_all2" title="Отметить/снять все" value="Y" name="check_all"></th>
		<th width="4%">Имя</th>
		<th>E-Mail</th>
		<th width="15%">Доставлено:</th>
		<th width="15%">&nbsp;</th>
	</tr>
	<?php
		foreach($vars['list'] as $row)
		{
			if($row['delivered']==1)$active='Да';
			else $active='Нет';
			
			echo'<tr id="sort'.$row['usermail_id'].'">
					<td class="center"><input type="checkbox" class="check-item" value="'.$row['usermail_id'].'" name="id[]" /></td>
					<td><span>'.$row['usermail_id'].'</span></td>
					<td><input type="text" value="'.$row['email'].'" name="name[]" class="input-text"></td>
					<td><input type="hidden" value="'.$row['usermail_id'].'" name="save_id[]" />
						<div class="select-popup-container active_status" id="active'.$row['usermail_id'].'">'.$active.' </div>
					</td>
					<td width="10%">	
						<ul class="cm-tools-list tools-list">
							<li><a href="/admin/'.$vars['action'].'/delete/'.$row['usermail_id'].'" class="cm-confirm">Удалить</a></li>
						</ul>
					</td>
				</tr>';
		}
	?>
</table>
</div>
<div class="table-tools">
	<a class="check_all" href="javascript:void(0);">Выбрать все</a>| 
	<a class="uncheck_all" href="javascript:void(0);">Снять выделение со всех</a>
</div>