<div class="items-container multi-level">
<table width="100%" cellspacing="0" cellpadding="0" border="0" class="table table-fixed hidden-inputs tb_sort">
	<tr>
		<th width="20" class="center"><input type="checkbox" class="check_all2" title="Отметить/снять все" value="Y" name="check_all"></th>
		<th width="30">ID</th>
		<th width="150">Дата</th>
		<th>Сообщение</th>
		<th width="170" style="text-align:center;">Действие</th>
	</tr>
	<?php
		foreach($vars['list'] as $row)
		{
			echo'<tr>
					<td class="center"><input type="checkbox" class="check-item" value="'.$row['id'].'" name="id[]" /></td>
					<td><span>'.$row['id'].'</span></td>
					<td><span>'.$row['date'].'</span></td>
					<td><span>'.mb_substr(strip_tags($row['text']), 0, 105, "utf-8").'... </span></td>
					<td width="10%">
						<input type="hidden" value="'.$row['id'].'" name="save_id[]" />
						<a href="/admin/'.$vars['action'].'/edit/'.$row['id'].'" class="tool-link">Просмотр</a>
						&nbsp;&nbsp;|		
						<ul class="cm-tools-list tools-list">
							<li><a href="/admin/'.$vars['action'].'/delete/'.$row['id'].'" class="cm-confirm">Удалить</a></li>
						</ul>
					</td>
                </tr>';
		}
	?>
</table>

</div>

<div class="table-tools">
	<a class="check_all" href="javascript:void(0);">Выбрать все</a>| 
	<a class="uncheck_all" href="javascript:void(0);">Снять выделение со всех</a>
</div>
<?=$vars['paging']?>