<div class="items-container multi-level">
<table width="100%" cellspacing="0" cellpadding="0" border="0" class="table table-fixed hidden-inputs tb_sort">
	<tr>
		<th width="3%" class="center"><input type="checkbox" class="check_all2" title="Отметить/снять все" value="Y" name="check_all"></th>
		<th width="2%">ID</th>
		<th>Название</th>
		<th width="10%">Символ</th>
		<th width="10%">Курс</th>
		<th width="12%">Базовая валюта</th>
		<th width="15%">Позиция символа</th>
		<th width="5%">&nbsp;</th>
	</tr>
	<?php
		foreach($vars['list'] as $row)
		{
            echo'<tr>
                    <td class="center"><input type="checkbox" class="check-item" value="'.$row['id'].'" name="id[]" /></td>
                    <td><span>'.$row['id'].'</span><input type="hidden" value="'.$row['id'].'" name="save_id[]" /></td>
                    <td><input type="text" value="'.$row['name'].'" name="name[]" class="input-text"></td>
					<td><input type="text" value="'.$row['icon'].'" name="icon[]" class="input-text" style="width:50px;" /></td>
                    <td><input type="text" value="'.$row['rate'].'" name="rate[]" class="input-text" style="width:50px;" /></td>
					<td style="padding-left:48px;"><input type="radio" value="'.$row['id'].'" name="base"';if($row['base']==1)echo' checked="checked"';echo' /></td>
					<td>
						<select name="position[]">
							<option value="0"';if($row['position']==0)echo' selected';echo'>Перед ценой</option>
							<option value="1"';if($row['position']==1)echo' selected';echo'>После цены</option>
						</select>
					</td>
                    <td width="10%">
                        <ul class="cm-tools-list tools-list">
                            <li><a href="/admin/'.$vars['action'].'/delete/'.$row['id'].'" class="cm-confirm">Удалить</a></li>
                        </ul>
                    </td>
                </tr>';
		}
	?>
</table>
</div>
<div class="table-tools">
	<a class="check_all" href="javascript:void(0);">Выбрать все</a>| 
	<a class="uncheck_all" href="javascript:void(0);">Снять выделение со всех</a>
</div>