<div class="cm-notification-container"></div>
<?=$vars['message']?>
<div class="cm-tabs-content">
	<div class="clear mainbox-title-container">
		<h1 class="mainbox-title">Новые мета данные:&nbsp;</h1>
	</div>
	<div class="extra-tools">
		
	</div>
	<div class="mainbox-body"> 
		
        <div class="tabs cm-j-tabs cm-track">
            <ul>
                <li id="basic" class="cm-js cm-active"><a >Общее</a></li>
                <li id="metadata" class="cm-js"><a >Мета данные</a></li>
            </ul>
        </div>
        <form class="cm-form-highlight cm-check-changes" name="page_update_form" method="post" action="">
            <div id="content_basic" class="cm-tabs">
                <fieldset>
                    <h2 class="subheader"> Информация </h2>
                    <div class="form-field">
                        <label for="page">URL:</label>
                        <input type="text" class="input-text-large main-input" value="" size="55" name="url" />
                    </div>
                    <div class="form-field">
                        <label for="page_descr">Краткое описание:</label>
                        <?= showEditor('excerpt', '', '2'); ?>
                    </div>
                    <div class="form-field">
                        <label for="page_descr">Описание:</label>
                        <?=showEditor('body', '');?>
                    </div>
                    <div class="form-field">
                        <label class="cm-required">Статус:</label>
                        <div class="select-field">
                            <input type="radio" class="radio" value="1" id="page_data_0_a" name="active" checked="checked" />
                            <label for="page_data_0_a">Вкл.</label>
                            <input type="radio" class="radio" value="0" id="page_data_0_d" name="active" />
                            <label for="page_data_0_d">Выкл.</label>
                        </div>
                    </div>
                </fieldset>
            </div>
            <!--Basic end-->
            
            <!--text_page start-->
            <div id="content_metadata" class="cm-tabs hidden">         
                <fieldset>
                    <h2 class="subheader"> Meta данные </h2>
                    <div class="form-field">
                        <label for="page_page_title">Заголовок раздела:</label>
                        <input type="text" class="input-text-large" value="" size="55" id="page_page_title" name="title" />
                    </div>
                    <div class="form-field">
                        <label for="page_meta_keywords">META ключевые слова:</label>
                        <textarea class="input-textarea-long" rows="2" cols="55" id="page_meta_keywords" name="keywords"></textarea>
                    </div>
                    <div class="form-field">
                        <label for="page_meta_descr">META описание:</label>
                        <textarea class="input-textarea-long" rows="2" cols="55" id="page_meta_descr" name="description"></textarea>
                    </div>
                </fieldset>
            </div>
            <div class="buttons-container cm-toggle-button buttons-bg">
                <div class="cm-buttons-floating hidden" style="display: block;">
                    <div class="cm-buttons-placeholder">
                        <span class="submit-button cm-button-main">
                            <input type="submit" value="Создать" name="add" />
                        </span>&nbsp;
                        <span class="submit-button cm-button-main cm-save-and-close">
                            <input type="submit" value="Создать и закрыть" name="add_close" class="cm-save-and-close" />
                        </span> &nbsp;или&nbsp;&nbsp; 
                        <a class="underlined tool-link" href="/admin/<?=$vars['action']?>">Отменить</a>
                    </div>
                </div>
            </div>
            <input type="hidden" value="<?=$vars['action']?>" id="action" />
        </form>
	</div>
</div>