<div class="cm-notification-container"></div>
<?=$vars['message']?>
<div class="cm-tabs-content">
	<div class="clear mainbox-title-container">
		<h1 class="mainbox-title">Редактирование мета данных</h1>
	</div>
	<div class="extra-tools">
	
	<a class="tool-link" href="/admin/<?=$vars['action']?>/add">Добавить</a>
	<a class="tool-link" href="/admin/<?=$vars['action']?>/edit/<?=$vars['edit']['id']?>/duplicate">Дублировать эти мета данные</a>
    <a class="tool-link cm-confirm" href="/admin/<?=$vars['action']?>/delete/<?=$vars['edit']['id']?>">Удалить эти мета данные</a>
		<div class="float-right preview-link">
			<a href="<?=$vars['edit']['url']?>" title="<?=$vars['edit']['url']?>" class="tool-link" target="_blank">Предпросмотр</a>
		</div>
	</div>
	<div class="mainbox-body"> 
		
        <div class="tabs cm-j-tabs cm-track">
            <ul>
                <li id="basic" class="cm-js cm-active"><a >Общее</a></li>
                <li id="metadata" class="cm-js"><a >Мета данные</a></li>
            </ul>
        </div>
        <form class="cm-form-highlight cm-check-changes" name="page_update_form" method="post" action="">
            <input type="hidden" value="<?=$vars['edit']['id']?>" name="id" />
            <div id="content_basic" class="cm-tabs">
                <fieldset>
                    <h2 class="subheader"> Информация </h2>
                    <div class="form-field">
                        <label class="cm-required" for="page">URL:</label>
                        <input type="text" class="input-text-large main-input" value="<?=$vars['edit']['url']?>" size="55" name="url" />
                    </div>
                    <div class="form-field">
                        <label for="page_excerpt">Краткое описание:</label>
                        <?=showEditor('excerpt', $vars['edit']['excerpt'], '2'); ?>
                    </div>
                    <div class="form-field">
                        <label for="page_descr">Описание:</label>
                        <?=showEditor('body', $vars['edit']['body']);?>
                    </div>
                    <div class="form-field">
                        <label class="cm-required">Статус:</label>
                        <div class="select-field">
                            <input type="radio" class="radio" value="1" id="page_data_0_a" name="active" <? if($vars['edit']['active']==1)echo' checked="checked"';?>>
                            <label for="page_data_0_a">Вкл.</label>
                            <input type="radio" class="radio" value="0" id="page_data_0_d" name="active" <? if($vars['edit']['active']==0)echo' checked="checked"';?>>
                            <label for="page_data_0_d">Выкл.</label>
                        </div>
                    </div>
                    <div class="form-field">
                        <label class="cm-required">Тип: </label>
                        <div class="select-field">
                            <input type="radio" class="radio" value="0" id="page_d0" name="type" <? if($vars['edit']['type']==0)echo' checked="checked"';?>>
                            <label for="page_d1">Выкл.</label>
                            
                            <input type="radio" class="radio" value="2" id="page_d2" name="type" <? if($vars['edit']['type']==2)echo' checked="checked"';?>>
                            <label for="page_d2">Префикс</label>
                            
                            <input type="radio" class="radio" value="3" id="page_d3" name="type" <? if($vars['edit']['type']==3)echo' checked="checked"';?>>
                            <label for="page_d3">Суффикс</label>
                            
                            <input type="radio" class="radio" value="1" id="page_d1" name="type" <? if($vars['edit']['type']==1)echo' checked="checked"';?>>
                            <label for="page_d1">Мета данные по умолчанию</label>
                        </div>
                    </div>
                </fieldset>
            </div>
            <!--Basic end-->
            
            <!--text_page start-->
            <div id="content_metadata" class="cm-tabs hidden">      
                <fieldset>
                    <h2 class="subheader"> Meta данные </h2>
                    <div class="form-field">
                        <label for="page_page_title">Заголовок раздела:</label>
                        <input type="text" class="input-text-large" value="<?=$vars['edit']['title']?>" size="55" id="page_page_title" name="title" />
                    </div>
                    <div class="form-field">
                        <label for="page_meta_keywords">META ключевые слова:</label>
                        <textarea class="input-textarea-long" rows="2" cols="55" id="page_meta_keywords" name="keywords"><?=$vars['edit']['keywords']?></textarea>
                    </div>
                    <div class="form-field">
                        <label for="page_meta_descr">META описание:</label>
                        <textarea class="input-textarea-long" rows="2" cols="55" id="page_meta_descr" name="description"><?=$vars['edit']['description']?></textarea>
                    </div>
                </fieldset>
            </div>
            <div class="buttons-container cm-toggle-button buttons-bg">
                <div class="cm-buttons-floating hidden" style="display: block;">
                    <div class="cm-buttons-placeholder">
                        <span class="submit-button cm-button-main">
                            <input type="submit" value="Сохранить" name="update" />
                        </span>&nbsp;
                        <span class="submit-button cm-button-main cm-save-and-close">
                            <input type="submit" value="Сохранить и закрыть" name="update_close" class="cm-save-and-close" />
                        </span> &nbsp;или&nbsp;&nbsp; 
                        <a class="underlined tool-link" href="/admin/<?=$vars['action']?>">Отменить</a>
                    </div>
                </div>
            </div>
            <input type="hidden" value="<?=$vars['action']?>" id="action" />
        </form>
	</div>
</div>