<div class="cm-notification-container"></div>
<div id="message"><?=$vars['message']?></div>
<div>
	<div class="clear mainbox-title-container">
		<div class="tools-container"><span class="action-add"> <a href="/admin/<?=$vars['action']?>/subsystem/translate/addsubsystem">Добавить</a> </span> </div>
		<h1 class="mainbox-title float-left">Интерфейс "<?=$vars['modules_name']?>"</h1>
	</div>
	</div>
	<div class="mainbox-body">
		<div id="ds_15014" class="clear">
			
		</div>
		<div id="content_manage_users">
			<form name="userlist_form" method="post" action="/admin/<?=$vars['action']?>/subsystem/translate/update">
				<div id="pagination_contents">
                    <div class="items-container multi-level">
                    <table width="100%" cellspacing="0" cellpadding="0" border="0" class="table table-fixed hidden-inputs tb_sort">
                        <tr>
                            <th width="20" class="center"><input type="checkbox" class="check_all2" title="Отметить/снять все" value="Y" name="check_all"></th>
                            <th width="30">ID</th>
                            <th width="140">Ключ</th>
                            <th width="230">Значение</th>
                            <th width="230">Комментарий</th>
                            <th>Модуль</th>
                            <th width="60">Действие</th>
                        </tr>
                        <?php
                            foreach($vars['list'] as $row)
                            {
                                echo'<tr>
                                        <td class="center"><input type="checkbox" class="check-item" value="'.$row['id'].'" name="id[]" /></td>
										<td><span>'.$row['id'].'</span><input type="hidden" value="'.$row['id'].'" name="save_id[]" /></td>
										<td><input type="text" value="'.$row['key'].'" name="key[]" class="input-text" style="width:120px;"></td>
										<td><textarea name="value[]" class="input-textarea" style="resize: none; height:17px; width:200px;">'.$row['value'].'</textarea></td>
										<td><textarea name="comment[]" class="input-textarea" style="resize: none; height:17px; width:200px;">'.$row['comment'].'</textarea></td>
										<td>
											<select name="modules_id[]" style="width:160px;"><option value="">...</option>';
											foreach($vars['modules'] as $row2)
											{
												echo'<option value="'.$row2['id'].'"';if($row2['id']==$row['modules_id'])echo' selected';echo'>'.$row2['name'].'</option>';	
											}
											echo'</select>
										</td>
										<td>
											<ul class="cm-tools-list tools-list">
												<li><a href="/admin/'.$vars['action'].$vars['path'].'/delsubsystem/'.$row['id'].'" class="cm-confirm">Удалить</a></li>
											</ul>
										</td>
                                    </tr>';
                            }
                        ?>
                    </table>
                    </div>
                    <div class="table-tools">
                        <a class="check_all" href="javascript:void(0);">Выбрать все</a>| 
                        <a class="uncheck_all" href="javascript:void(0);">Снять выделение со всех</a>
                    </div>
                    
                </div>
				<div class="buttons-container buttons-bg">
                <div class="cm-buttons-floating hidden" style="display: block;">
					<div class="cm-buttons-placeholder">
						<div class="float-left">
							<span class="submit-button cm-button-main">
								<input type="submit" value="Сохранить" name="update" class="">
							</span>или
							<span class="submit-button cm-button-main cm-confirm cm-process-items">
								<input type="submit" value="Удалить выбранные" name="delete" class="cm-process-items">
							</span>
						</div>
					</div>
					<div class="cm-buttons-floating hidden"></div>
				</div>
                </div>
				<input type="hidden" value="<?=$vars['action']?>" id="action" />
			</form>
			</div>
		</div>
	</div>
</div>