<div class="items-container multi-level">
<table width="100%" cellspacing="0" cellpadding="0" border="0" class="table table-fixed hidden-inputs tb_sort">
	<tr>
		<th width="20" class="center"><input type="checkbox" class="check_all2" title="Отметить/снять все" value="Y" name="check_all"></th>
		<th width="30">ID</th>
		<th width="140">Ключ</th>
		<th width="230">Значение</th>
        <th width="230">Комментарий</th>
        <th>Модуль</th>
		<th width="60">Действие</th>
	</tr>
	<?php
		foreach($vars['list'] as $row)
		{
            echo'<tr>
                    <td class="center"><input type="checkbox" class="check-item" value="'.$row['id'].'" name="id[]" /></td>
                    <td><span>'.$row['id'].'</span><input type="hidden" value="'.$row['id'].'" name="save_id[]" /></td>
                    <td><input type="text" value="'.$row['key'].'" name="key[]" class="input-text" style="width:120px;"></td>
                    <td><textarea name="value[]" class="input-textarea" style="resize: none; height:17px; width:200px;">'.$row['value'].'</textarea></td>
                    <td><textarea name="comment[]" class="input-textarea" style="resize: none; height:17px; width:200px;">'.$row['comment'].'</textarea></td>
					<td>
						<select name="modules_id[]" style="width:160px;"><option value="">...</option>';
						foreach($vars['modules'] as $row2)
						{
							echo'<option value="'.$row2['id'].'"';if($row2['id']==$row['modules_id'])echo' selected';echo'>'.$row2['name'].'</option>';	
						}
						echo'</select>
					</td>
                    <td>
                        <ul class="cm-tools-list tools-list">
                            <li><a href="/admin/'.$vars['action'].'/delete/'.$row['id'].$vars['path'].'" class="cm-confirm">Удалить</a></li>
                        </ul>
                    </td>
                </tr>';
		}
	?>
</table>
</div>
<div class="table-tools">
	<a class="check_all" href="javascript:void(0);">Выбрать все</a>| 
	<a class="uncheck_all" href="javascript:void(0);">Снять выделение со всех</a>
</div>