<div class="cm-notification-container"></div>
<?=$vars['message']?>
<div>
	<div class="clear mainbox-title-container">
		<h1 class="mainbox-title">Редактирование статьи:&nbsp;<?=$vars['edit']['name']?></h1>
	</div>
	<div class="extra-tools">
	
	<a class="tool-link" href="/admin/<?=$vars['action']?>/add">Добавить статью</a>
    <a class="tool-link cm-confirm" href="/admin/<?=$vars['action']?>/delete/<?=$vars['edit']['id']?>">Удалить этот статью</a>
		<div class="float-right preview-link">
			<a href="/article/<?=$vars['edit']['url']?>" title="<?=$vars['edit']['url']?>" class="tool-link" target="_blank">Предпросмотр</a>
		</div>
	</div>
	<div class="mainbox-body"> 
		<div class="cm-tabs-content">
			<form class="cm-form-highlight cm-check-changes" name="page_update_form" method="post" action="">
				<input type="hidden" value="<?=$vars['edit']['id']?>" name="id" />
				<div id="content_basic" style="display: block;">
					<fieldset>
						<h2 class="subheader"> Информация </h2>
						<div class="form-field">
							<label class="cm-required" for="page">Название:</label>
							<input type="text" class="input-text-large main-input" value="<?=$vars['edit']['name']?>" size="55" name="name" />
						</div>
						<div class="form-field">
							<label class="cm-required" for="page">URL:</label>
							<input type="text" class="input-text-large main-input" value="<?=$vars['edit']['url']?>" size="55" name="url" />
						</div>
						<div class="form-field">
							<label class="cm-required" for="page">Дата:</label>
							<input type="text" class="input-text cm-calendar hasDatepicker" value="<?=$vars['edit']['date']?>" size="55" name="date" id="news_date" />
							<img alt="Календарь" title="Календарь" rev="news_date" class="cm-external-focus calendar-but" src="/tpl/admin/images/icons/calendar.png">
						</div>
						<div class="form-field">
							<label for="body_m">Краткое описание:</label>
							<textarea class="input-textarea-long" rows="10" cols="55" id="body_m" name="body_m"><?=$vars['edit']['body_m']?></textarea>
						</div>
						<div class="form-field">
							<label for="page_descr">Описание:</label>
							<?=showEditor('body', $vars['edit']['body']);?>
						</div>

						<div class="form-field">
							<label class="cm-required">Статус:</label>
							<div class="select-field">
								<input type="radio" class="radio" value="1" id="page_data_0_a" name="active" <? if($vars['edit']['active']==1)echo' checked="checked"';?>>
								<label for="page_data_0_a">Вкл.</label>
								<input type="radio" class="radio" value="0" id="page_data_0_d" name="active" <? if($vars['edit']['active']==0)echo' checked="checked"';?>>
								<label for="page_data_0_d">Выкл.</label>
							</div>
						</div>
					</fieldset>
					<fieldset>
						<h2 class="subheader">Обложка</h2>
						<div class="form-field">
							<?php
								/*
								if(file_exists($dir[0]."{$vars['edit']['id']}_s.jpg"))$src="/".$dir[0]."{$vars['edit']['id']}_s.jpg";
								else $src="/tpl/admin/images/no_image.gif";<label for="page_page_title"><img src="<?=$src?>?<?=date("Y-m-d-H-i-s");?>" alt="" style="max-width: 150px;" /></label>
								<input type="file" name="photo" />*/
								
								$vars['path']="files/news/";
								$vars['image_id']=$vars['edit']['id'];
								include $_SERVER['DOCUMENT_ROOT']."/tpl/admin/upload_img.phtml";
							?>
						</div>
					</fieldset>
					<fieldset>
						<h2 class="subheader"> Meta данные </h2>
						<div class="form-field">
							<label for="page_page_title">Заголовок раздела:</label>
							<input type="text" class="input-text-large" value="<?=$vars['edit']['title']?>" size="55" id="page_page_title" name="title" />
						</div>
						<div class="form-field">
							<label for="page_meta_keywords">META ключевые слова:</label>
							<textarea class="input-textarea-long" rows="2" cols="55" id="page_meta_keywords" name="keywords"><?=$vars['edit']['keywords']?></textarea>
						</div>
						<div class="form-field">
							<label for="page_meta_descr">META описание:</label>
							<textarea class="input-textarea-long" rows="2" cols="55" id="page_meta_descr" name="description"><?=$vars['edit']['description']?></textarea>
						</div>
					</fieldset>
				</div>
				<div class="buttons-container cm-toggle-button buttons-bg">
					<div class="cm-buttons-floating hidden" style="display: block;">
						<div class="cm-buttons-placeholder">
							<span class="submit-button cm-button-main">
								<input type="submit" value="Сохранить" name="update" />
							</span>&nbsp;
							<span class="submit-button cm-button-main cm-save-and-close">
								<input type="submit" value="Сохранить и закрыть" name="update_close" class="cm-save-and-close" />
							</span> &nbsp;или&nbsp;&nbsp; 
							<a class="underlined tool-link" href="/admin/<?=$vars['action']?>">Отменить</a>
						</div>
					</div>
				</div>
				<input type="hidden" value="<?=$vars['action']?>" id="action" />
			</form>
		</div>
	</div>
</div>