<div class="cm-notification-container"></div>
<?=$vars['message']?>
<div>
	<div class="clear mainbox-title-container">
		<h1 class="mainbox-title">Новый фильтр:&nbsp;</h1>
	</div>
	<div class="extra-tools">
		
	</div>
	<div class="mainbox-body"> 
		<div class="cm-tabs-content">
			<form class="cm-form-highlight cm-check-changes" name="page_update_form" method="post" action="">
				<div id="content_basic" style="display: block;">
					<fieldset>
						<h2 class="subheader"> Информация </h2>
						<div class="form-field">
							<label class="cm-required" for="page">Название:</label>
							<input type="text" class="input-text-large main-input" value="" style="width:200px;" name="name" />
						</div>
						<div class="form-field">
							<label class="cm-required" for="page">URL:</label>
							<input type="text" class="input-text-large main-input" value="" style="width:200px;" name="url" />
						</div>
						<div class="form-field">
                            <label class="cm-required" for="page">Раздел:</label>
                            <select name="sub">
                                <option value="0">Корень...</option>
                                <?php
                                foreach($vars['params'] as $row)
                                {
                                	echo"<option value='{$row['id']}'";if($row['id']==$_SESSION['sort_params'])echo" selected";echo">{$row['name']}</option>";
                                }
                                ?>
                            </select>
						</div>
                        <div class="form-field">
							<label for="page">Цвет:</label>
							<input type="text" class="input-text-large main-input" value="" name="rgb" id="colorpickerField1" style="width:55px; margin-right:5px;" />
                            <span id="cur_color" style="padding: 2px 10px 1px 10px; border: 1px solid #000; background-color: #;"></span>
						</div>
                        <div class="form-field">
							<label for="page_descr">Описание:</label>
							<?=showEditor('body', '');?>
						</div>
						<div class="form-field">
							<label class="cm-required">Статус:</label>
							<div class="select-field">
								<input type="radio" class="radio" value="1" id="page_data_0_a" name="active" checked="checked">
								<label for="page_data_0_a">Вкл.</label>
								<input type="radio" class="radio" value="0" id="page_data_0_d" name="active" >
								<label for="page_data_0_d">Выкл.</label>
							</div>
						</div>
					</fieldset>
                    <fieldset>
                        <h2 class="subheader">Тип группы фильтров</h2>
                        <div style="margin-left:15px; max-height:300px; overflow:auto;">
                            <?php
								echo'<input name="type" type="radio" id="type0" value="" checked="checked"><label for="type0">&nbsp;</label><br />';
								foreach($vars['types'] as $row)
								{
									echo'<input name="type" type="radio" id="type'.$row['id'].'" value="'.$row['url'].'">
										 <label for="type'.$row['id'].'">'.$row['name'].'</label><br />';	
								}
                                
                            ?>
                        </div>
                    </fieldset>
				</div>
				<div class="buttons-container cm-toggle-button buttons-bg">
					<div class="cm-buttons-floating hidden" style="display: block;">
						<div class="cm-buttons-placeholder">
							<span class="submit-button cm-button-main">
								<input type="submit" value="Создать" name="add" />
							</span>&nbsp;
							<span class="submit-button cm-button-main cm-save-and-close">
								<input type="submit" value="Создать и закрыть" name="add_close" class="cm-save-and-close" />
							</span> &nbsp;или&nbsp;&nbsp; 
							<a class="underlined tool-link" href="/admin/<?=$vars['action']?>">Отменить</a>
						</div>
					</div>
				</div>
				<input type="hidden" value="<?=$vars['action']?>" id="action" />
			</form>
		</div>
	</div>
</div>