<div class="cm-notification-container"></div>
<div id="message">
  <?=$vars['message']?>
</div>
<div>
  <div class="clear mainbox-title-container">
    <h1 class="mainbox-title float-left">
      <?=$vars['name']?>
    </h1>
  </div>
  <div class="mainbox-body">
    <div id="ds_15014" class="clear"></div>
    <div id="content_manage_users">
      <div id="pagination_contents"><?php echo $vars['list'];?></div>
    </div>
  </div>
</div>