<div class="items-container multi-level">
<table width="100%" cellspacing="0" cellpadding="0" border="0" class="table table-fixed hidden-inputs tb_sort">
	<tr class="noDrop">
        <th width="25"></th>
 		<th width="20">ID</th>
		<th>Название</th>
		<th width="170">KEY</th>
        <th width="150">Default</th>
		<th width="100">&nbsp;</th>
	</tr>
	<?php
		foreach($vars['list'] as $row)
		{
			 ?>
             <tr id="sort <?=$row['id']?>">
					<td class="move"></td>
                     <td><span><?=$row['id']?></span><input type="hidden" value="<?=$row['id']?>" name="save_id[]" /></td>
                    <td><input type="text" value="<?=$row['comment']?>" name="comment[]" class="input-text"></td>
					<td>
						 <?=$row['language'];?>
					</td>
					<td>
						 <input name="default[]" <?=$row['default']==1?'checked="checked"':''?> value="<?=$row['id']?>"  type="radio"/>
					</td>
                    <td width="10%">
                        <ul class="cm-tools-list tools-list">
                            <li><a href="/admin/<?=$vars['action'];?>/delete/<?=$row['id'];?>" class="cm-confirm">Удалить</a></li>
                        </ul>
                    </td>
                </tr><?
		}
	?>
</table>
</div>
 