<div class="cm-notification-container"></div>
<?=$vars['message']?>
<div class="cm-tabs-content">
	<div class="clear mainbox-title-container">
		<h1 class="mainbox-title">Редактирование раздел меню:&nbsp;<?=$vars['edit']['name']?></h1>
	</div>
	<div class="extra-tools">
	
	<a class="tool-link" href="/admin/menu/add">Добавить раздел</a>
    <a class="tool-link cm-confirm" href="/admin/menu/delete/<?=$vars['edit']['id']?>">Удалить этот раздел</a>
		<div class="float-right preview-link">
			<a href="/<?=$vars['edit']['url']?>" title="<?=$vars['edit']['url']?>" class="tool-link" target="_blank">Предпросмотр</a>
		</div>
	</div>
	<div class="mainbox-body"> 
        <div class="tabs cm-j-tabs cm-track">
            <ul>
                <li id="basic" class="cm-js cm-active"><a >Общее</a></li>
                <li id="metadata" class="cm-js"><a >Мета данные</a></li>
                <?
                    if(isset($vars['comments'])&&$vars['comments']!='')echo'<li id="comments" class="cm-js"><a >Комментарии</a></li>';
                ?>
            </ul>
        </div>
        <form class="cm-form-highlight cm-check-changes" name="page_update_form" method="post" action="">
            <input type="hidden" value="<?=$vars['edit']['id']?>" name="id" />
            <div id="content_basic" class="cm-tabs">
                <fieldset>
                    <h2 class="subheader"> Информация </h2>
                    <div class="form-field">
                        <label for="elm_parent_id" class="cm-required">Родительская раздел:</label>
                        <select id="elm_parent_id" name="sub">
                            <option value="0">- Корневой раздел -</option>
                            <?php echo $vars['select_tree'];?>
                        </select>
                    </div>
                    <div class="form-field">
                        <label class="cm-required" for="page">Название:</label>
                        <input type="text" class="input-text-large main-input" value="<?=$vars['edit']['name']?>" size="55" name="name" />
                    </div>
                    <div class="form-field">
                        <label class="cm-required" for="page">URL:</label>
                        <input type="text" class="input-text-large main-input" value="<?=$vars['edit']['url']?>" size="55" name="url" />
                    </div>
                    <div class="form-field">
                        <label for="page_descr">Описание:</label>
                        <?=showEditor('body', $vars['edit']['body']);?>
                    </div>
                    <div class="form-field">
                        <label class="cm-required">Подключить модуль:</label>
                        <div class="select-field">
                            <input type="radio" class="radio" value="0" id="form0" name="form" <? if($vars['edit']['form']==0)echo' checked="checked"';?>>
                            <label for="form0">Выкл.</label>
                            
                            <input type="radio" class="radio" value="1" id="form1" name="form" <? if($vars['edit']['form']==1)echo' checked="checked"';?>>
                            <label for="form1">Обратная связь</label>
                            
                            <input type="radio" class="radio" value="2" id="form2" name="form" <? if($vars['edit']['form']==2)echo' checked="checked"';?>>
                            <label for="form2">Комментарии</label>
                        </div>
                    </div>
                    <div class="form-field">
                        <label class="cm-required">Статус:</label>
                        <div class="select-field">
                            <input type="radio" class="radio" value="0" id="page_data_0_a" name="active" <? if($vars['edit']['active']==0)echo' checked="checked"';?>>
                            <label for="page_data_0_a">Выкл.</label>
                            <input type="radio" class="radio" value="1" id="page_data_0_d" name="active" <? if($vars['edit']['active']==1)echo' checked="checked"';?>>
                            <label for="page_data_0_d">Вкл.</label>
                        </div>
                    </div>
                </fieldset>
            </div>
             <!--metdata start-->
            <div id="content_metadata" class="cm-tabs hidden">
                <fieldset>
                    <h2 class="subheader"> Meta данные </h2>
                    <div class="form-field">
                        <label for="page_page_title">Заголовок раздела:</label>
                        <input type="text" class="input-text-large" value="<?=$vars['edit']['title']?>" size="55" id="page_page_title" name="title" />
                    </div>
                    <div class="form-field">
                        <label for="page_meta_keywords">META ключевые слова:</label>
                        <textarea class="input-textarea-long" rows="2" cols="55" id="page_meta_keywords" name="keywords"><?=$vars['edit']['keywords']?></textarea>
                    </div>
                    <div class="form-field">
                        <label for="page_meta_descr">META описание:</label>
                        <textarea class="input-textarea-long" rows="2" cols="55" id="page_meta_descr" name="description"><?=$vars['edit']['description']?></textarea>
                    </div>
                </fieldset>
            </div>
            <!--metdata end-->
            
            <?
				if(isset($vars['comments']))echo '<div id="comments_load">'.$vars['comments'].'</div>';
			?>
            <div class="buttons-container cm-toggle-button buttons-bg">
                <div class="cm-buttons-floating hidden" style="display: block;">
                    <div class="cm-buttons-placeholder">
                        <span class="submit-button cm-button-main">
                            <input type="submit" value="Сохранить" name="update" />
                        </span>&nbsp;
                        <span class="submit-button cm-button-main cm-save-and-close">
                            <input type="submit" value="Сохранить и закрыть" name="update_close" class="cm-save-and-close" />
                        </span> &nbsp;или&nbsp;&nbsp; 
                        <a class="underlined tool-link" href="/admin/menu">Отменить</a>
                    </div>
                </div>
            </div>
            <input type="hidden" value="<?=$vars['action']?>" id="action" />
        </form>
	</div>
</div>