<div class="items-container multi-level">
<table width="100%" cellspacing="0" cellpadding="0" border="0" class="table table-fixed hidden-inputs tb_sort">
	<tr>
		<th width="20" class="center"><input type="checkbox" class="check_all2" title="Отметить/снять все" value="Y" name="check_all"></th>
        <th width="30">ID</th>
        <th width="180">Ключ</th>
        <th>Значение</th>
        <th>Комментарий</th>
        <th width="150">Модуль / Тип поля</th>
        <th width="60">Действие</th>
	</tr>
	<?php
		foreach($vars['list'] as $row)
		{
			$input='';
			if($row['type']=='text')$input='<input type="text" name="value'.$row['id'].'" value="'.$row['value'].'" class="input-text" style="width:190px;" />';
			elseif($row['type']=='checkbox')
			{
				$checked='';
				if($row['value']==1)$checked=' checked="checked"';
				$input='<label class="switch">
							<input type="checkbox" name="value'.$row['id'].'" value="1" '.$checked.' class="switch-input"  />
							<span class="switch-label" data-on="Да" data-off="Нет"></span>
							<span class="switch-handle"></span>
						</label>';
			}
			elseif($row['type']=='radio')
			{
				$checked0='';
				$checked1='';
				if($row['value']==1)$checked1=' checked="checked"';
				else $checked0=' checked="checked"';
				
				$input='<input type="radio" name="value'.$row['id'].'" value="0" '.$checked0.' />
					    <input type="radio" name="value'.$row['id'].'" value="1" '.$checked1.' />';
			}
			elseif($row['type']=='textarea')$input='<textarea name="value'.$row['id'].'" class="input-textarea" style="resize: none; height:17px; width:190px;">'.$row['value'].'</textarea>';
			
            echo'<tr>
                    <td class="center"><input type="checkbox" class="check-item" value="'.$row['id'].'" name="id[]" /></td>
                    <td><span>'.$row['id'].'</span><input type="hidden" value="'.$row['id'].'" name="save_id[]" /></td>
                    <td><input type="text" value="'.$row['name'].'" name="name[]" class="input-text" style="width:150px;"></td>
                    <td>'.$input.'</td>

					<td><textarea name="comment[]" class="input-textarea" style="resize: none; height:17px; width:200px;">'.$row['comment'].'</textarea></td>
					<td>
						
						
						<select name="modules_id[]" style="width:160px; margin-bottom:3px;"><option value="">...</option>';
						foreach($vars['modules'] as $row2)
						{
							echo'<option value="'.$row2['id'].'"';if($row2['id']==$row['modules_id'])echo' selected';echo'>'.$row2['name'].'</option>';	
						}
						echo'</select>
						
						<select name="type_id[]" style="width:160px;"><option value="text">text</option>';
							echo'<option value="textarea"';if($row['type']=='textarea')echo' selected';echo'>textarea</option>';	
							echo'<option value="checkbox"';if($row['type']=='checkbox')echo' selected';echo'>checkbox</option>';	
						echo'</select>
					</td>
                    <td width="10%">
                        <ul class="cm-tools-list tools-list">
                            <li><a href="/admin/'.$vars['action'].'/delete/'.$row['id'].$vars['path'].'" class="cm-confirm">Удалить</a></li>
                        </ul>
                    </td>
                </tr>';
		}
	?>
</table>
</div>
<div class="table-tools">
	<a class="check_all" href="javascript:void(0);">Выбрать все</a>| 
	<a class="uncheck_all" href="javascript:void(0);">Снять выделение со всех</a>
</div>