<div class="items-container multi-level">
<table width="100%" cellspacing="0" cellpadding="0" border="0" class="table table-fixed hidden-inputs tb_sort">
	<tr>
		<th width="3%" class="center"><input type="checkbox" class="check_all2" title="Отметить/снять все" value="Y" name="check_all"></th>
		<th width="2%">ID</th>
		<th width="23%">Ключ</th>
		<th width="23%">Значение</th>
        <th>Комментарий</th>
		<th width="8%">&nbsp;</th>
	</tr>
	<?php
		foreach($vars['list'] as $row)
		{
            echo'<tr>
                    <td class="center"><input type="checkbox" class="check-item" value="'.$row['id'].'" name="id[]" /></td>
                    <td><span>'.$row['id'].'</span><input type="hidden" value="'.$row['id'].'" name="save_id[]" /></td>
                    <td><input type="text" value="'.$row['name'].'" name="name[]" class="input-text"></td>
                    <td><input type="text" value="'.$row['value'].'" name="value[]" class="input-text"></td>
                    <td><input type="text" value="'.$row['comment'].'" name="comment[]" class="input-text" style="width:350px;" /></td>
                    <td width="10%">
                        <ul class="cm-tools-list tools-list">
                            <li><a href="/admin/'.$vars['action'].'/delete/'.$row['id'].'" class="cm-confirm">Удалить</a></li>
                        </ul>
                    </td>
                </tr>';
		}
	?>
</table>
</div>
<div class="table-tools">
	<a class="check_all" href="javascript:void(0);">Выбрать все</a>| 
	<a class="uncheck_all" href="javascript:void(0);">Снять выделение со всех</a>
</div>