<div class="cm-notification-container"></div>
<?=$vars['message']?>
<div>
	<div class="clear mainbox-title-container">
		<h1 class="mainbox-title">Новая страница:&nbsp;</h1>
	</div>
	<div class="extra-tools">
		
	</div>
	<div class="mainbox-body"> 
		<div class="cm-tabs-content">
			<form class="cm-form-highlight cm-check-changes" name="page_update_form" method="post" action="" enctype="multipart/form-data">
				<div id="content_basic" style="display: block;">
					<fieldset>
						<h2 class="subheader"> Информация </h2>
						<div class="form-field">
							<label class="cm-required" for="page">Название:</label>
							<input type="text" class="input-text-large main-input" value="" size="55" name="name" />
						</div>
						<div class="form-field">
							<label for="page">URL:</label>
							<input type="text" class="input-text-medium main-input" value="" size="55" name="url" />
						</div>
						<div class="form-field">
                            <label for="page">Артикул:</label>
                            <input type="text" class="input-text-medium" value="" size="55" name="code" />
                        </div>
						<div class="form-field">
                            <label for="page">Цена:</label>
                            <input type="text" class="input-text-medium" value="" size="55" name="price" /> <?=$vars['currency']['icon']?>
                        </div>
						<div class="form-field">
                            <label for="page">Скидка:</label>
                            <input type="text" class="input-text-medium" value="" size="55" name="discount" style="width:30px;" /> %
                        </div>
						<div class="form-field">
							<label for="page_descr">Описание:</label>
							
							<?=$this->showEditor('body', '');?>
						</div>
						<div class="form-field">
							<label for="page_descr">Характеристики:</label>
							<textarea name="body_m" id="elm2" rows="20" cols="94"></textarea>
						</div>
						<div class="form-field">
							<label class="cm-required">Статус:</label>
							<div class="select-field">
								<input type="radio" class="radio" value="0" id="page_data_0_a" name="active" checked="checked" />
								<label for="page_data_0_a">Вкл.</label>
								<input type="radio" class="radio" value="1" id="page_data_0_d" name="active" />
								<label for="page_data_0_d">Выкл.</label>
							</div>
						</div>
					</fieldset>
					<fieldset>
						<h2 class="subheader">Каталог</h2>
						<div style="margin-left:15px;">
                            <?php
                                foreach($vars['catalog'] as $row)
                                {
									if($row['sub']==0)
									{
										echo' <input name="cat_id[]" type="checkbox" id="cat'.$row['id'].'" value="'.$row['id'].'">
											  <label for="cat'.$row['id'].'">'.$row['name'].'</label><br />';
										
										 foreach($vars['catalog'] as $row2)
										{
											if($row['id']==$row2['sub'])
											{
												echo'&nbsp;&nbsp;&nbsp;&nbsp;<input name="cat_id[]" type="checkbox" id="cat'.$row2['id'].'" value="'.$row2['id'].'">
													 <label for="cat'.$row2['id'].'">'.$row2['name'].'</label><br />';
											}
										}
									}
                                }
                            ?>
						</div>
					</fieldset>
					
					<fieldset>
						<h2 class="subheader">Настройки</h2>
						<div style="margin-left:15px;">
                            <?php
                                foreach($vars['status'] as $row)
                                {
									echo' <input name="status_id[]" type="checkbox" id="status'.$row['id'].'" value="'.$row['id'].'">
										  <label for="status'.$row['id'].'">'.$row['comment'].'</label><br />';
                                }
                            ?>
						</div>
					</fieldset>
                    <fieldset>
                        <h2 class="subheader">Обложка</h2>
                        <div class="form-field">
                            <?php
                            	$src="/tpl/admin/images/no_image.gif";
                            ?>
                            <label for="page_page_title"><img src="<?=$src?>" alt="" style="max-width: 150px;" /></label>
                            <input type="file" name="photo" />
                        </div>
                    </fieldset>
					<fieldset>
						<h2 class="subheader"> SEO / Meta данные </h2>
						<div class="form-field">
							<label for="page_page_title">Заголовок раздела:</label>
							<input type="text" class="input-text-large" value="" size="55" id="page_page_title" name="title" />
						</div>
						<div class="form-field">
							<label for="page_meta_keywords">META ключевые слова:</label>
							<textarea class="input-textarea-long" rows="2" cols="55" id="page_meta_keywords" name="keywords"></textarea>
						</div>
						<div class="form-field">
							<label for="page_meta_descr">META описание:</label>
							<textarea class="input-textarea-long" rows="2" cols="55" id="page_meta_descr" name="description"></textarea>
						</div>
					</fieldset>
				</div>
				<div class="buttons-container cm-toggle-button buttons-bg">
					<div class="cm-buttons-floating hidden" style="display: block;">
						<div class="cm-buttons-placeholder">
							<span class="submit-button cm-button-main">
								<input type="submit" value="Создать" name="add" />
							</span>&nbsp;
							<span class="submit-button cm-button-main cm-save-and-close">
								<input type="submit" value="Создать и закрыть" name="add_close" class="cm-save-and-close" />
							</span> &nbsp;или&nbsp;&nbsp; 
							<a class="underlined tool-link" href="/admin/<?=$vars['action']?>">Отменить</a>
						</div>
					</div>
				</div>
				<input type="hidden" value="<?=$vars['action']?>" id="action" />
			</form>
		</div>
	</div>
</div>