<div class="cm-notification-container"></div>
<?=$vars['message']?>
<div>
	<div class="clear mainbox-title-container">
		<h1 class="mainbox-title">Новый товар:&nbsp;</h1>
	</div>
	<div class="extra-tools">
		
	</div>
	<div class="mainbox-body"> 
        <div class="tabs cm-j-tabs cm-track">
            <ul>
                <li id="basic" class="cm-js cm-active"><a >Общее</a></li>
                <li id="text_page" class="cm-js"><a >Описание</a></li>
                <li id="metadata" class="cm-js"><a >Мета данные</a></li>
                <li id="price" class="cm-js"><a >Цены</a></li>
                <li id="images" class="cm-js"><a >Изображения</a></li>
                <?
                    if(isset($vars['params']))echo'<li id="params" class="cm-js"><a >Фильтры</a></li>';
                    if(isset($vars['comments'])&&$vars['comments']!='')echo'<li id="comments" class="cm-js"><a >Комментарии</a></li>';
                ?>
            </ul>
        </div>
        
		<div class="cm-tabs-content">
			<form class="cm-form-highlight cm-check-changes" name="page_update_form" method="post" action="" enctype="multipart/form-data">
				<div id="content_basic" class="cm-tabs">
					<fieldset>
						<h2 class="subheader"> Информация </h2>
						<div class="form-field">
							<label class="cm-required" for="page">Название:</label>
							<input type="text" class="input-text-large main-input" value="" size="55" name="name" />
						</div>
						<div class="form-field">
							<label for="page">URL:</label>
							<input type="text" class="input-text-medium main-input" value="" size="55" name="url" />
						</div>
						<div class="form-field">
                            <label for="page">Артикул:</label>
                            <input type="text" class="input-text-medium" value="" size="55" name="code" />
                        </div>
                        <div class="form-field">
                            <label for="page">Цена:</label>
                            <input type="text" class="input-text-medium" value="" size="55" name="price" />
                        </div>
                        <div class="form-field">
                            <label for="page">Скидка:</label>
                            <input type="text" class="input-text-medium" value="" size="55" name="discount" />
                        </div>
                        <div class="form-field">
                            <label for="page">Ед. измерения:</label>
                            <input type="text" class="input-text-medium" value="" size="55" name="unit" />
                        </div>
                        <div class="form-field">
                            <label for="page">На складе:</label>
                            <input type="text" class="input-text-medium" value="" size="55" name="stock" />
                        </div>

						<div class="form-field">
							<label class="cm-required">Статус:</label>
							<div class="select-field">
								<input type="radio" class="radio" value="1" id="page_data_0_a" name="active" checked="checked" />
								<label for="page_data_0_a">Вкл.</label>
								<input type="radio" class="radio" value="0" id="page_data_0_d" name="active" />
								<label for="page_data_0_d">Выкл.</label>
							</div>
						</div>
					</fieldset>
					<fieldset>
						<h2 class="subheader">Каталог</h2>
						<div style="margin-left:15px; max-height:300px; overflow:auto;">
                            <?php
                                foreach($vars['catalog'] as $row)
                                {
									if($row['sub']==0)
									{
										echo' <input name="cat_id[]" type="checkbox" id="cat'.$row['id'].'" value="'.$row['id'].'">
											  <label for="cat'.$row['id'].'">'.$row['name'].'</label><br />';
										
										 foreach($vars['catalog'] as $row2)
										{
											if($row['id']==$row2['sub'])
											{
												echo'&nbsp;&nbsp;&nbsp;&nbsp;<input name="cat_id[]" type="checkbox" class="cat'.$row['id'].'" id="cat'.$row2['id'].'" value="'.$row2['id'].'">
													 <label for="cat'.$row2['id'].'">'.$row2['name'].'</label><br />';
												
												foreach($vars['catalog'] as $row3)
												{
													if($row2['id']==$row3['sub'])
													{
														echo'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input name="cat_id[]" type="checkbox" class="cat'.$row2['id'].'" id="cat'.$row3['id'].'" value="'.$row3['id'].'">
														<label for="cat'.$row3['id'].'">'.$row3['name'].'</label><br />';
													}
												}	 
											}
										}
									}
                                }
                            ?>
						</div>
					</fieldset>
					<?
						if(isset($vars['brend']))
						{
							echo'<fieldset>
								 <h2 class="subheader">Бренды</h2>
								 <div style="margin-left:15px; max-height:300px; overflow:auto;">
								 <select name="brend_id" style="width:150px;">
								 	<option value="0">Выберите бренд...</option>';
							foreach($vars['brend'] as $row)
							{
								echo'<option value="'.$row['id'].'">'.$row['name'].'</option>';
							}
							echo'</select></div>
								 </fieldset>';	
						}
					?>
					<fieldset>
						<h2 class="subheader">Настройки</h2>
						<div style="margin-left:15px;">
                            <?php
                                foreach($vars['status'] as $row)
                                {
									echo' <input name="status_id[]" type="checkbox" id="status'.$row['id'].'" value="'.$row['id'].'">
										  <label for="status'.$row['id'].'">'.$row['comment'].'</label><br />';
                                }
                            ?>
						</div>
					</fieldset>
				</div>
				<!--Basic end-->
                
                <!--text_page start-->
				<div id="content_text_page" class="cm-tabs hidden">
					<fieldset>
                    	<h2 class="subheader">Описание товара</h2>
						<div class="form-field">
							<label for="body_m">Краткое описание:</label>
							<? //showEditor('body_m', $vars['edit']['body_m'], 'elm2');?>
                            <textarea class="input-textarea-long" rows="5" cols="75" id="body_m" name="body_m"></textarea>
						</div>
                        <div class="form-field">
							<label for="page_descr">Полное описание:</label>
							<?=showEditor('body', '');?>
						</div>
					</fieldset>
				</div>
				<!--text_page end-->
                
                <!--metdata start-->
				<div id="content_metadata" class="cm-tabs hidden">
                    <fieldset>
                        <h2 class="subheader"> Meta данные </h2>
                        <div class="form-field">
                            <label for="page_page_title">Заголовок раздела:</label>
                            <input type="text" class="input-text-large" value="" size="55" id="page_page_title" name="title" />
                        </div>
                        <div class="form-field">
                            <label for="page_meta_keywords">META ключевые слова:</label>
                            <textarea class="input-textarea-long" rows="2" cols="55" id="page_meta_keywords" name="keywords"></textarea>
                        </div>
                        <div class="form-field">
                            <label for="page_meta_descr">META описание:</label>
                            <textarea class="input-textarea-long" rows="2" cols="55" id="page_meta_descr" name="description"></textarea>
                        </div>
                    </fieldset>
				</div>
				<!--metdata end-->
                
                <!--Price start-->
				<div id="content_price" class="cm-tabs hidden">
					<fieldset>
                        <h2 class="subheader">Цены</h2>

                            <?=$vars['price']?>

                    </fieldset>
				</div>
				<!--Price end-->
				<!--Images start-->
				<div id="content_images" class="cm-tabs hidden">
					<fieldset>
                        <h2 class="subheader">Обложка</h2>
                        <div class="form-field">
                            <?php
								/*
								if(file_exists($dir[0]."{$vars['edit']['id']}_s.jpg"))$src="/".$dir[0]."{$vars['edit']['id']}_s.jpg";
								else $src="/tpl/admin/images/no_image.gif";<label for="page_page_title"><img src="<?=$src?>?<?=date("Y-m-d-H-i-s");?>" alt="" style="max-width: 150px;" /></label>
								<input type="file" name="photo" />*/
								$path="files/tmp/";
								$vars['path']=$path;
								$vars['image_id']=mktime();
								$_SESSION['tmp_image'] = $vars['image_id'];
								include $_SERVER['DOCUMENT_ROOT']."/tpl/admin/upload_img.phtml";
                            ?>
                            <input type="hidden" name="tmp_image" value="<?=$vars['image_id']?>" />
                        </div>
                    </fieldset>
				</div>
				<!--Images end-->

				<? if(isset($vars['params']))echo $vars['params'];?>
				<div class="buttons-container cm-toggle-button buttons-bg">
					<div class="cm-buttons-floating hidden" style="display: block;">
						<div class="cm-buttons-placeholder">
							<span class="submit-button cm-button-main">
								<input type="submit" value="Создать" name="add" />
							</span>&nbsp;
							<span class="submit-button cm-button-main cm-save-and-close">
								<input type="submit" value="Создать и открыть" name="add_open" class="cm-save-and-close" />
							</span> &nbsp;или&nbsp;&nbsp; 
							<a class="underlined tool-link" href="/admin/<?=$vars['action']?>">Отменить</a>
						</div>
					</div>
				</div>
				<input type="hidden" value="<?=$vars['action']?>" id="action" />
			</form>
		</div>
	</div>
</div>