<div class="cm-notification-container"></div>
<?=$vars['message']?>
<div class="cm-tabs-content">
	<div class="clear mainbox-title-container">
		<h1 class="mainbox-title">Редактирование товара:&nbsp;<?=$vars['edit']['name']?></h1>
	</div>
	<div class="extra-tools">
	<a class="tool-link cm-confirm" href="/admin/<?=$vars['action']?>/delete/<?=$vars['edit']['id']?>">Удалить этот товар</a>
	<a class="tool-link" href="/admin/<?=$vars['action']?>/add">Добавить товар</a>
		<div class="float-right preview-link">
			<a href="/product/<?=$vars['edit']['url']?>" title="<?=$vars['edit']['url']?>" class="tool-link" target="_blank">Предпросмотр</a>
		</div>
	</div>
	<div class="mainbox-body"> 
	<div class="tabs cm-j-tabs cm-track">
		<ul>
			<li id="basic" class="cm-js cm-active"><a >Общее</a></li>
			<li id="images" class="cm-js"><a >Изображения</a></li>
			<?
				if(isset($vars['params']))echo'<li id="params" class="cm-js"><a >Фильтры</a></li>';
			?>
		</ul>
	</div>

			<form class="cm-form-highlight cm-check-changes" name="page_update_form" method="post" action="" enctype="multipart/form-data">
				<input type="hidden" value="<?=$vars['edit']['id']?>" name="id" />
				
				<!--Basic start-->
				<div id="content_basic" class="cm-tabs">
					<fieldset>
						<h2 class="subheader"> Информация </h2>
						<div class="form-field">
							<label class="cm-required" for="page">Название:</label>
							<input type="text" class="input-text-large main-input" value="<?=$vars['edit']['name']?>" size="55" name="name" />
						</div>
						<div class="form-field">
							<label class="cm-required" for="page">URL:</label>
							<input type="text" class="input-text-large main-input" value="<?=$vars['edit']['url']?>" size="55" name="url" />
						</div>
                        <div class="form-field">
                            <label for="page">Артикул:</label>
                            <input type="text" class="input-text-medium" value="<?=$vars['edit']['code']?>" size="55" name="code" />
                        </div>
						<div class="form-field">
                            <label for="page">Цена:</label>
                            <input type="text" class="input-text-medium" value="<?=$vars['edit']['price']?>" size="55" name="price" /> <?=$vars['currency']['icon']?>
                        </div>
						<div class="form-field">
                            <label for="page">Скидка:</label>
                            <input type="text" class="input-text-medium" value="<?=$vars['edit']['discount']?>" size="55" name="discount" style="width:30px;" /> %
                        </div>
						<div class="form-field">
							<label for="page_descr">Описание:</label>
							<?=$this->showEditor('body', $vars['edit']['body']);?>
						</div>
						<div class="form-field">
							<label for="page_descr">Характеристики:</label>
							<textarea name="body_m" id="elm2" rows="20" cols="94"><?=$vars['edit']['body_m']?></textarea>
						</div>
						<div class="form-field">
							<label class="cm-required">Статус:</label>
							<div class="select-field">
								<input type="radio" class="radio" value="1" id="page_data_0_a" name="active" <? if($vars['edit']['active']==1)echo' checked="checked"';?>>
								<label for="page_data_0_a">Вкл.</label>
								<input type="radio" class="radio" value="0" id="page_data_0_d" name="active" <? if($vars['edit']['active']==0)echo' checked="checked"';?>>
								<label for="page_data_0_d">Выкл.</label>
							</div>
						</div>
					</fieldset>
					<fieldset>
						<h2 class="subheader">Каталог</h2>
						<div style="margin-left:15px;">
                            <?php
                                foreach($vars['catalog'] as $row)
                                {
									if($row['sub']==0)
									{
										echo' <input name="cat_id[]" type="checkbox" id="cat'.$row['id'].'" value="'.$row['id'].'"';
										if($row['product_id']==$vars['edit']['id'])echo' checked="checked"';echo'><label for="cat'.$row['id'].'">'.$row['name'].'</label><br />';
										
										 foreach($vars['catalog'] as $row2)
										{
											if($row['id']==$row2['sub'])
											{
												echo'&nbsp;&nbsp;&nbsp;&nbsp;<input name="cat_id[]" type="checkbox" id="cat'.$row2['id'].'" value="'.$row2['id'].'"';
												if($row2['product_id']==$vars['edit']['id'])echo' checked="checked"';echo'><label for="cat'.$row2['id'].'">'.$row2['name'].'</label><br />';
											}
										}
									}
                                }
                            ?>
						</div>
					</fieldset>
					
					<fieldset>
						<h2 class="subheader">Настройки</h2>
						<div style="margin-left:15px;">
                            <?php
                                foreach($vars['status'] as $row)
                                {
									echo' <input name="status_id[]" type="checkbox" id="status'.$row['id'].'" value="'.$row['id'].'"';
									if($row['product_id']!='')echo' checked="checked"';echo'><label for="status'.$row['id'].'">'.$row['comment'].'</label><br />';
                                }
                            ?>
						</div>
					</fieldset>
                    
                    <fieldset>
                        <h2 class="subheader"> SEO / Meta данные </h2>
                        <div class="form-field">
                            <label for="page_page_title">Заголовок раздела:</label>
                            <input type="text" class="input-text-large" value="<?=$vars['edit']['title']?>" size="55" id="page_page_title" name="title" />
                        </div>
                        <div class="form-field">
                            <label for="page_meta_keywords">META ключевые слова:</label>
                            <textarea class="input-textarea-long" rows="2" cols="55" id="page_meta_keywords" name="keywords"><?=$vars['edit']['keywords']?></textarea>
                        </div>
                        <div class="form-field">
                            <label for="page_meta_descr">META описание:</label>
                            <textarea class="input-textarea-long" rows="2" cols="55" id="page_meta_descr" name="description"><?=$vars['edit']['description']?></textarea>
                        </div>
                    </fieldset>
				</div>
				<!--Basic end-->
				
				<!--Images start-->
				<div id="content_images" class="cm-tabs hidden">
					<fieldset>
                        <h2 class="subheader">Обложка</h2>
                        <div class="form-field">
                            <?php
								/*
								if(file_exists($dir[0]."{$vars['edit']['id']}_s.jpg"))$src="/".$dir[0]."{$vars['edit']['id']}_s.jpg";
								else $src="/tpl/admin/images/no_image.gif";<label for="page_page_title"><img src="<?=$src?>?<?=date("Y-m-d-H-i-s");?>" alt="" style="max-width: 150px;" /></label>
								<input type="file" name="photo" />*/
								$path=createDir($vars['edit']['id']);
								$vars['path']=$path[0];
								$vars['image_id']=$vars['edit']['id'];
								include $_SERVER['DOCUMENT_ROOT']."/tpl/admin/upload_img.phtml";
                            ?>
                            
                        </div>
                    </fieldset>
                   
					<fieldset>
                        <h2 class="subheader">Доп. Фото</h2>

                            <?=$vars['photo']?>

                    </fieldset>
				</div>
				<!--Images end-->
				
				<? if(isset($vars['params']))echo $vars['params'];?>
				
				<div class="buttons-container cm-toggle-button buttons-bg">
					<div class="cm-buttons-floating hidden" style="display: block;">
						<div class="cm-buttons-placeholder">
							<span class="submit-button cm-button-main">
								<input type="submit" value="Сохранить" name="update" />
							</span>&nbsp;
							<span class="submit-button cm-button-main">
								<input type="submit" value="Сохранить и закрыть" name="update_close" class="cm-save-and-close-product" />
							</span> &nbsp;или&nbsp;&nbsp; 
							<a class="underlined tool-link" href="/admin/<?=$vars['action']?>">Отменить</a>
						</div>
					</div>
				</div>
			</form>

	</div>
</div>