<div class="cm-notification-container"></div>
<div id="message"><?=$vars['message']?></div>
<div>
	<div class="clear mainbox-title-container">
		<div class="tools-container"><span class="action-add"> <a href="/admin/<?=$vars['action']?>/add">Добавить</a> </span> </div>
		<h1 class="mainbox-title float-left"><?=$vars['name']?></h1>
	</div>
	</div>
	<div class="mainbox-body">
		<div id="ds_15014" class="clear">
        <div class="section-border">
        <form class="cm-disable-empty " method="POST" name="search_form" action="">
        <table cellspacing="0" border="0" class="search-header">
            <tr>
                <td class="nowrap search-field">
                    <label>Найти:<?=$_SESSION['search']['word']?></label>
                    <div class="break">
                        <input type="text" class="search-input-text" value="<?=$_SESSION['search']['word']?>" size="20" name="word" />
                        <input type="image" title="Поиск" alt="Поиск" class="search-go" src="/tpl/admin/images/search_go.gif">&nbsp;
                    </div>
                </td>
                <td class="nowrap search-field">
                    <label>Цена&nbsp;:</label>
                    <div class="break">
                        <input type="text" class="input-text-price" onfocus="this.select();" value="<?=$_SESSION['search']['price_from']?>" size="1" name="price_from">&nbsp;&ndash;&nbsp;
                        <input type="text" class="input-text-price" onfocus="this.select();" value="<?=$_SESSION['search']['price_to']?>" name="price_to" size="1">
                    </div>
                </td>
                <td class="nowrap search-field">
                    <label>Поиск в категории:</label>
                    <div class="break clear correct-picker-but">
                        <select name="cat_id">
                            <option value="0">- Все категории -</option>
                            <?php
                                foreach($vars['catalog'] as $row)
                                {
									if($row['sub']==0)
									{
										echo"<option value='{$row['id']}'";if($row['id']==$_SESSION['search']['cat_id'])echo" selected";echo">{$row['name']}</option>";
										foreach($vars['catalog'] as $row2)
										{
											if($row['id']==$row2['sub'])
											{
												echo"<option value='{$row2['id']}'";if($row2['id']==$_SESSION['search']['cat_id'])echo" selected";echo">&nbsp;&nbsp;&nbsp;{$row2['name']}</option>";
												foreach($vars['catalog'] as $row3)
												{
													if($row2['id']==$row3['sub'])
													{
														echo"<option value='{$row3['id']}'";if($row3['id']==$_SESSION['search']['cat_id'])echo" selected";echo">&nbsp;&nbsp;&nbsp; - {$row3['name']}</option>";
													}
												}
											}
										}
									}
                                }
                            ?>
                        </select>
                    </div>
                </td>
                <td class="buttons-container">
					<span class="submit-button "><input type="submit" value="Поиск" name="dispatch[products.manage]"></span>
                    <span class="submit-button "><input type="submit" value="Очистить" name="clear"></span>
					
                </td>
            </tr>
            </table>
        </form>
        </div>
		</div>
		<div id="content_manage_users">
			<form name="userlist_form" method="post" action="/admin/<?=$vars['action']?>/update">
				<div id="pagination_contents">
					<?php echo $vars['list'];?>
				</div>
				<div class="buttons-container buttons-bg">
					<div class="cm-buttons-placeholder">
						<div class="float-left">
							<span class="submit-button cm-button-main">
								<input type="submit" value="Сохранить" name="update" class="">
							</span>или
							<span class="submit-button cm-button-main cm-confirm cm-process-items">
								<input type="submit" value="Удалить выбранные" name="delete" class="cm-process-items">
							</span>
						</div>
					</div>
					<div class="cm-buttons-floating hidden"></div>
				</div>
				<input type="hidden" value="<?=$vars['action']?>" id="action" />
			</form>
			</div>
		</div>
	</div>
</div>