<script type="text/javascript">
    $(document).ready(function() {
        $("#uploadify").uploadify({
            'uploader'       : '/files/flash/uploadify.swf',
            'script'         : '/ajaxadmin/uploadifyproduct',
            'cancelImg'      : '/tpl/admin/images/cancel.png',
            'folder'         : '/tpl/admin/images',
            'scriptData'	 : {'id':'<?=$vars['edit']['id']?>'},
            'queueID'        : 'fileQueue',
            'auto'           : true,
            'multi'          : true,
            'onComplete'	 : function (evt, queueID, fileObj, response, data){
                var dataString = 'id=<?=$vars['edit']['id']?>';
                $.ajax
                    ({
                        type: "POST",
                        url: "/ajaxadmin/photoproduct",
                        data: dataString,
                        cache: false,
                        success: function(html)
                        {
                            $("#photos").html(html);
                            $("#photos").tableDnD({onDragClass:"hover"});
                        }
                    });
            }
        });
    });
</script>
<table><tr><td valign="top">
<div id="fileQueue"></div>
<input type="file" name="uploadify" id="uploadify" />

</td>
    <td valign="top">
    <table width="750" cellspacing="0" cellpadding="0" border="0" class="table table-fixed hidden-inputs tb_sort" id="photos" style="margin-top: 0;">
        <tr class="noDrop">
            <th width="25"></th>
            <th width="20" class="center"><input type="checkbox" class="check_all2" title="Отметить/снять все" value="Y" name="check_all"></th>
            <th width="20">ID</th>
            <th width="50">Фото</th>
            <th>Название</th>
            <th width="100">Статус</th>
            <th width="80">&nbsp;</th>
        </tr>
        <?php
        foreach($vars['photo'] as $row)
        {
            if($row['active']==1)$active='<div class="selected-status status-a"><a> Вкл. </a></div>';
            else $active='<div class="selected-status status-d"><a> Выкл. </a></div>';
            $dir=createDir($row['product_id']);
            echo'<tr id="sort'.$row['id'].'">
					<td class="move"></td>
					<td class="center"><input type="checkbox" class="check-item" value="'.$row['id'].'" name="photo_id[]" /></td>
					<td><span>'.$row['id'].'</span></td>
					<td><img src="/'.$dir['1'].'/'.$row['id'].'_s.jpg" alt="" width="50" /></td>
					<td><input type="text" value="'.$row['name'].'" name="photo_name[]" class="input-text"></td>
					<td><input type="hidden" value="'.$row['id'].'" name="save_photo_id[]" />
						<div class="select-popup-container active_status" id="active'.$row['id'].'">'.$active.' </div>
					</td>
					<td width="10%">
						<ul class="cm-tools-list tools-list">
							<li><a href="/admin/'.$vars['action'].'/edit/'.$row['product_id'].'/delete/'.$row['id'].'" class="cm-confirm">Удалить</a></li>
						</ul>
					</td>
				</tr>';
        }
        ?>
    </table>

<div class="table-tools">
    <a class="check_all" href="javascript:void(0);">Выбрать все</a>|
    <a class="uncheck_all" href="javascript:void(0);">Снять выделение со всех</a>
    <span class="submit-button cm-button-main"><input type="submit" name="dell" value="Удалить выбранные" class="cm-confirm" /></span>
</div>
<input type="hidden" value="product_photo" id="action" />
    </td></tr></table>