<div class="items-container multi-level">
    <table width="100%" cellspacing="0" cellpadding="0" border="0" class="table table-fixed hidden-inputs tb_sort">
        <tr class="noDrop">
        	<th width="25"></th>
            <th width="20" class="center"><input type="checkbox" class="check_all2" title="Отметить/снять все" value="Y" name="check_all"></th>
            <th width="50">ID</th>
            <th width="80" class="center">Фото</th>
            <th>Название</th>
			<th width="150">Каталог</th>
			<th width="100">Цена (грн.)</th>
            <th width="100">Статус</th>
            <th width="180">&nbsp;</th>
        </tr>
        <?php
        foreach($vars['list'] as $row)
        {
            if($row['active']==1)$active='<div class="selected-status status-a"><a> Вкл. </a></div>';
            else $active='<div class="selected-status status-d"><a> Выкл. </a></div>';

            $dir=createDir($row['id']);
            if(file_exists($dir[0]."{$row['id']}_s.jpg"))$src="/".$dir[0]."{$row['id']}_s.jpg";
            else $src="/tpl/admin/images/no_image.gif";

           echo'<tr id="sort'.$row['id'].'">
					<td class="move"></td>
					<td class="center"><input type="checkbox" class="check-item" value="'.$row['id'].'" name="id[]" /></td>
					<td><span>'.$row['id'].'</span></td>
					<td><a href="/admin/'.$vars['action'].'/edit/'.$row['id'].'"><img src="'.$src.'" width="60" /></a></td>
					<td><a href="/admin/'.$vars['action'].'/edit/'.$row['id'].'" class="strong">'.$row['name'].'</a>
						<div>
							<span class="product-code-label">Арт. товара: </span>
							<input type="text" class="input-text product-code" value="'.$row['code'].'" name="code[]" style="width:100px;">
						</div>
					</td>
					<td>'.$row['catalog'].'</td>
					<td><input type="text" value="'.$row['price'].'" name="price[]" class="input-text" style="width:90px;" /></td>
					<td><input type="hidden" value="'.$row['id'].'" name="save_id[]" />
						<div class="select-popup-container active_status" id="active'.$row['id'].'">'.$active.' </div>
					</td>
					<td width="10%">
						<a href="/admin/'.$vars['action'].'/edit/'.$row['id'].'" class="tool-link">Редактировать</a>
						&nbsp;&nbsp;|		
						<ul class="cm-tools-list tools-list">
							<li><a href="/admin/'.$vars['action'].'/delete/'.$row['id'].'" class="cm-confirm">Удалить</a></li>
						</ul>
					</td>
				</tr>';
        }
        ?>
    </table>
</div>
<div class="table-tools">
    <a class="check_all" href="javascript:void(0);">Выбрать все</a>|
    <a class="uncheck_all" href="javascript:void(0);">Снять выделение со всех</a>
</div>
<? echo $vars['paging']?>
