<link rel="stylesheet" type="text/css" href="/tpl/<?=theme?>/css/comments.css" />
<div class="clear"></div>
<?php
	if(isset($_POST['logout2']))unset($_SESSION['user_comments']);
	if(isset($_POST['token']))
	{
		$s = file_get_contents('http://ulogin.ru/token.php?token=' . $_POST['token'] . '&host=' . $_SERVER['HTTP_HOST']);
		$user_data = json_decode($s, true);
		if(!isset($user_data['error']))
		{
			$_SESSION['user_comments'] = $user_data;
		}
	}
	
	if(isset($_SESSION['user_comments']['photo'])&&$_SESSION['user_comments']['photo']!='')$src=$_SESSION['user_comments']['photo'];
	else $src='/files/default.gif';
	
	echo'<div id="comment_block">';
		 
	if(!isset($_SESSION['user_comments'])&&!isset($_SESSION['user_id']))
	{
		?>
		<div class="cnt_comment title"><?=$vars['translate']['comments']?> <span>(<?=count($vars['comments'])?>)</span></div>
		<div id="soc_auth">
			<script src="http://ulogin.ru/js/ulogin.js" type="text/javascript"></script>
			<a href="#" id="uLogin" x-ulogin-params="display=window;fields=first_name,last_name,photo;redirect_uri=http%3A%2F%2F<?=$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI']?>">
            	<img src="http://ulogin.ru/img/button.png" width=187 height=30 alt="МультиВход" />
            </a>
		</div>
		<div id="input"></div>
		<div id="photo_comment"><img src="<?=$src?>" /></div>
		<div id="comment_form">
			<form method="post" action="" id="form_comment">
				<input type="text" value="" id="name_comment_form" class="validate[required]" placeholder="<?=$vars['translate']['name']?>" /><br />
				<input type="hidden" id="photo_comment" value="" />
				<input type="hidden" id="id_comment" value="<?=$vars['id']?>" />
				<input type="hidden" id="type_comment" value="<?=$vars['type']?>" />
				<textarea name="" id="text_comment_form" cols="30" rows="10" class="validate[required]" placeholder="<?=$vars['translate']['message']?>..."></textarea><br />
				<input type="submit" value="<?=$vars['translate']['send_message']?>" name="submit_comment" />
			</form>
		</div>
		<?
	}
	else{
		$name='';
		$photo='';
		if(isset($_SESSION['user_info']['email']))$name=$_SESSION['user_info']['name'];
		elseif(isset($_SESSION['user_comments']['first_name']))
		{
			$name=$_SESSION['user_comments']['first_name'].' '.$_SESSION['user_comments']['last_name'];
			$photo=$_SESSION['user_comments']['photo'];
		}
		?>
            <div class="cnt_comment title"><?=$vars['translate']['comments']?> <span>(<?=count($vars['comments'])?>)</span></div>
            <div id="input"></div>
            <div id="photo_comment">
            	<img src="<?=$src?>" width="50" />
                <form method="post">
                	<input type="hidden" name="logout2" value="1"><input type="image" src="/images/del.png" title="Logout" />
                </form>
            </div>
            <div id="comment_form">
                <form method="post" action="" id="form_comment">
                    <input type="hidden" value="<?=$name?>" id="name_comment_form" class="validate[required]" />
                    <input type="hidden" id="avatar" value="<?=$photo?>" />
                    <input type="hidden" id="id_comment" value="<?=$vars['id']?>" />
                    <input type="hidden" id="type_comment" value="<?=$vars['type']?>" />
                    <textarea name="" id="text_comment_form" cols="30" rows="10" class="validate[required]" placeholder="<?=$vars['translate']['message']?>..."></textarea><br />
                    <input type="submit" value="<?=$vars['translate']['send_message']?>" />
                </form>
            </div>
		<?
	}
	
	
	echo'<div class="clear"></div><br />
		 <div id="comment_list">';
		
		foreach($vars['comments'] as $row)
		{
			if($row['photo']!='')$src=$row['photo'];
			else $src='/files/default.gif';
			
			$answer='';
			if($row['text2']!='')
			{
				if($row['moderator_id']!=0&&file_exists("files/moderators/{$row['moderator_id']}_s.jpg"))$src2="/files/moderators/{$row['moderator_id']}_s.jpg";
				else $src2='/files/default.gif';
				
				$answer='
				<div class="comment_record answer_comment">
					<div class="photo_comment"><img src="'.$src2.'" width="50" /></div>
					<div class="info_comment">
						<div class="title_comment">'.$row['author2'].', '.Date::date_view($row['date'], "dd.mm.YY, hh:ii").'</div>
						<div class="text_comment">'.$row['text2'].'</div>
						
					</div>
					<div class="clear"></div>
				</div>
				';
			}
			echo'
			<div class="comment_record">
				<div class="photo_comment"><img src="'.$src.'" width="50" /></div>
				<div class="info_comment">
					<div class="title_comment">'.$row['author'].', '.Date::date_view($row['date'], "dd.mm.YY, hh:ii").'</div>
					<div class="text_comment">'.$row['text'].'</div>
					
				</div>
				<div class="clear"></div>
			</div>'.$answer;
		}
		
	echo'</div>
	</div>
	<div class="clear"></div>';
?>