<?
	if(file_exists($row['photo']))$src='<img alt="'.$row['name'].'" title="'.$row['name'].'" src="/'.$row['photo'].'" />';
	else $src='<img alt="" src="/files/default.jpg" />';
	
	$price=Numeric::viewPrice($row['price'], $row['discount']);

	if($row['stock']==NULL||$row['stock']==0)$status='<span class="status"><img src="'.IMAGES.'stock.png" alt="" /></span>';
	else $status='';
	
	$style='';
	if($i==3)
	{
		$style=' style="margin-right:0;"';
		$i=-1;	
	}
?>
    <div class="product"<?=$style?>>
		<? //=$status;?>
		<div class="photo_product">
			<a href="<?=LINK?>/product/<?=$row['url']?>"><?=$src?></a>
		</div>		
		<div class="info_product">
			<div class="name_product"><a href="<?=LINK?>/product/<?=$row['url']?>"><?=$row['name']?></a></div>
            <div class="prod-price"><?=$price['old_price'].$price['price'];?></div>
		</div>
		<div class="clear"></div>
	</div>