<div class="cm-notification-container"></div>
<?=$vars['message']?>
<div>
	<div class="clear mainbox-title-container">
		<h1 class="mainbox-title">Новая страница:&nbsp;</h1>
	</div>
	<div class="extra-tools">
		
	</div>
	<div class="mainbox-body"> 
		<div class="cm-tabs-content">
			<form class="cm-form-highlight cm-check-changes" name="page_update_form" method="post" action="" enctype="multipart/form-data">
				<div id="content_basic" style="display: block;">
					<fieldset>
						<h2 class="subheader"> Информация об учетной записи пользователя  </h2>
						<div class="form-field">
							<label class="cm-required" for="page">E-mail:</label>
							<input type="text" class="input-text" value="" size="32" name="email" />
						</div>
						<div class="form-field">
							<label class="cm-required" for="page">Пароль:</label>
							<input type="password" class="input-text" value="" size="32" name="password" />
						</div>
                        <div class="form-field">
                            <label class="cm-required" for="page">Подтвердите пароль:</label>
                            <input type="password" class="input-text" value="" size="32" name="password2" />
                        </div>

						<div class="form-field">
							<label class="cm-required">Статус:</label>
							<div class="select-field">
								<input type="radio" class="radio" value="0" id="page_data_0_a" name="active" checked="checked" />
								<label for="page_data_0_a">Вкл.</label>
								<input type="radio" class="radio" value="1" id="page_data_0_d" name="active" />
								<label for="page_data_0_d">Выкл.</label>
							</div>
						</div>
					</fieldset>
                    <fieldset>
                        <h2 class="subheader"> Личные данные  </h2>
                        <div class="form-field">
                            <label class="cm-required" for="page">Имя:</label>
                            <input type="text" class="input-text" value="" size="32" name="name" />
                        </div>
                        <div class="form-field">
                            <label for="page">Фамилия:</label>
                            <input type="text" class="input-text" value="" size="32" name="surname" />
                        </div>
                        <div class="form-field">
                            <label for="page">Отчество:</label>
                            <input type="text" class="input-text" value="" size="32" name="patronymic" />
                        </div>
                        <div class="form-field">
                            <label for="page_page_title">Доп. информация:</label>
                            <textarea class="input-textarea" rows="10" cols="55" name="info"></textarea>
                        </div>
                    </fieldset>
					<fieldset>
						<h2 class="subheader"> Контактные данные </h2>
                        <div class="form-field">
                            <label for="page">Телефон:</label>
                            <input type="text" class="input-text" value="" size="32" name="phone" />
                        </div>
                        <div class="form-field">
                            <label for="page">Skype:</label>
                            <input type="text" class="input-text" value="" size="32" name="skype" />
                        </div>
                        <div class="form-field">
                            <label for="page">Город:</label>
                            <input type="text" class="input-text" value="" size="32" name="city" />
                        </div>
                        <div class="form-field">
                            <label for="page">Адрес:</label>
                            <input type="text" class="input-text" value="" size="32" name="address" />
                        </div>
                        <div class="form-field">
                            <label for="page">Почтовый индекс:</label>
                            <input type="text" class="input-text" value="" size="32" name="post_index" />
                        </div>
					</fieldset>
				</div>
				<div class="buttons-container cm-toggle-button buttons-bg">
					<div class="cm-buttons-floating hidden" style="display: block;">
						<div class="cm-buttons-placeholder">
							<span class="submit-button cm-button-main">
								<input type="submit" value="Создать" name="add" />
							</span>&nbsp;
							<span class="submit-button cm-button-main cm-save-and-close">
								<input type="submit" value="Создать и закрыть" name="add_close" class="cm-save-and-close" />
							</span> &nbsp;или&nbsp;&nbsp; 
							<a class="underlined tool-link" href="/admin/<?=$vars['action']?>">Отменить</a>
						</div>
					</div>
				</div>
				<input type="hidden" value="<?=$vars['action']?>" id="action" />
			</form>
		</div>
	</div>
</div>