<div class="cm-notification-container"></div>
<?=$vars['message']?>
<div class="cm-tabs-content">
	<div class="clear mainbox-title-container">
		<h1 class="mainbox-title">Новый пользователь:&nbsp;</h1>
	</div>
	<div class="extra-tools">
		
	</div>
	<div class="mainbox-body"> 
		
        <div class="tabs cm-j-tabs cm-track">
            <ul>
                <li id="basic" class="cm-js cm-active"><a >Личные данные</a></li>
                <li id="params" class="cm-js"><a >Параметры</a></li>
            </ul>
        </div>
        <form class="cm-form-highlight cm-check-changes" name="page_update_form" method="post" action="" enctype="multipart/form-data">
            <div id="content_basic" class="cm-tabs">
                <fieldset>
                    <h2 class="subheader"> Личные данные  </h2>
                    <div class="form-field">
                        <label for="page">Имя:</label>
                        <input type="text" class="input-text" value="" size="32" name="name" autocomplete="off" />
                    </div>
                    <div class="form-field">
                        <label for="page">Фамилия:</label>
                        <input type="text" class="input-text" value="" size="32" name="surname" autocomplete="off" />
                    </div>
                    <div class="form-field">
                        <label for="page">Отчество:</label>
                        <input type="text" class="input-text" value="" size="32" name="patronymic" autocomplete="off" />
                    </div>
                    <div class="form-field">
                        <label for="page">Телефон:</label>
                        <input type="text" class="input-text" value="" size="32" name="phone" autocomplete="off" />
                    </div>
                    <div class="form-field">
                        <label for="page">E-mail:</label>
                        <input type="text" class="input-text" value="" size="32" name="email" autocomplete="off" />
                    </div>
                    <div class="form-field">
                        <label for="page">Город:</label>
                        <input type="text" class="input-text" value="" size="32" name="city" autocomplete="off" />
                    </div>
                    <div class="form-field">
                        <label for="page">Адрес:</label>
                        <input type="text" class="input-text" value="" size="32" name="address" autocomplete="off" />
                    </div>
                    <div class="form-field">
                        <label for="page">Почтовый индекс:</label>
                        <input type="text" class="input-text" value="" size="32" name="post_index" autocomplete="off" />
                    </div>
                    <div class="form-field">
                        <label for="page">Skype:</label>
                        <input type="text" class="input-text" value="" size="32" name="skype" autocomplete="off" />
                    </div>
                    <div class="form-field">
                        <label for="page_page_title">Доп. информация:</label>
                        <textarea class="input-textarea" rows="10" cols="55" name="info"></textarea>
                    </div>
                </fieldset>
            </div>
            <!--Basic end-->
            
            <!--text_page start-->
            <div id="content_params" class="cm-tabs hidden">
                <fieldset>
                    <h2 class="subheader"> Информация об учетной записи пользователя  </h2>
                    
                    <div class="form-field">
                        <label for="status_id">Статус пользователя:</label>
                        <select name="status_id" id="status_id" style="width:150px;">
                            <?
                                foreach($vars['status'] as $row)
                                {
                                    echo'<option value="'.$row['id'].'"';if($row['id']==$vars['price_type']['id'])echo' selected';echo'>'.$row['name'].'</option>';
                                }
                            ?>
                        </select>
                    </div>
                    <div class="form-field">
                        <label for="page">Пароль:</label>
                        <input type="password" class="input-text" value="" size="32" name="password" autocomplete="off" />
                    </div>
                    <div class="form-field">
                        <label for="page">Подтвердите пароль:</label>
                        <input type="password" class="input-text" value="" size="32" name="password2" autocomplete="off" />
                    </div>
                    
                    <div class="form-field">
                        <label for="page">Скидка:</label>
                        <input type="text" class="input-text" size="32" name="discount" />
                    </div>
                    <div class="form-field">
                        <label>Статус:</label>
                        <div class="select-field">
                            <input type="radio" class="radio" value="0" id="page_data_0_a" name="active" checked="checked" />
                            <label for="page_data_0_a">Вкл.</label>
                            <input type="radio" class="radio" value="1" id="page_data_0_d" name="active" />
                            <label for="page_data_0_d">Выкл.</label>
                        </div>
                    </div>
                </fieldset>
            </div>
            <div class="buttons-container cm-toggle-button buttons-bg">
                <div class="cm-buttons-floating hidden" style="display: block;">
                    <div class="cm-buttons-placeholder">
                        <span class="submit-button cm-button-main">
                            <input type="submit" value="Создать" name="add" />
                        </span>&nbsp;
                        <span class="submit-button cm-button-main cm-save-and-close">
                            <input type="submit" value="Создать и открыть" name="add_open" class="cm-save-and-close" />
                        </span> &nbsp;или&nbsp;&nbsp; 
                        <a class="underlined tool-link" href="/admin/<?=$vars['action']?>">Отменить</a>
                    </div>
                </div>
            </div>
            <input type="hidden" value="<?=$vars['action']?>" id="action" />
        </form>
	</div>
</div>