<div id="content_comments" class="cm-tabs hidden">
    <table width="100%" cellspacing="0" cellpadding="0" border="0" class="table table-fixed hidden-inputs tb_sort">
        <tr class="noDrop">
            <th width="20" class="center"><input type="checkbox" class="check_all2" title="Отметить/снять все" value="Y" name="check_all"></th>
            <th width="30">ID</th>
            <th width="120">Дата добавления</th>
            <th width="110">Автор</th>
            <th>Комментарий</th>
            <th width="170" style="text-align:center;">Действие</th>
        </tr>
        <?php
            foreach($vars['comments'] as $row)
            {
                if($row['active']==1)$active='<div class="selected-status status-a"><a> Вкл. </a></div>';
                else $active='<div class="selected-status status-d"><a> Выкл. </a></div>';
                
                echo'<tr>
                        <td class="center"><input type="checkbox" class="check-item comment_id" value="'.$row['id'].'" /></td>
                        <td><span>'.$row['id'].'</span></td>
                        <td>'.Date::date_view($row['date'], "dd/mm/YY, hh:ii").'</td>
                        <td><a href="/admin/comments/edit/'.$row['id'].'" target="_blank">'.$row['author'].'</a></td>
                        <td>'.mb_substr($row['text'], 0, 50, 'UTF-8').'...</td>
                        <td>
							<input type="hidden" value="'.$row['id'].'" name="save_id[]" />
                            <a href="/admin/comments/edit/'.$row['id'].'" class="tool-link" target="_blank">Редактировать</a>
                            &nbsp;&nbsp;|		
                            <ul class="cm-tools-list tools-list">
                                <li><a href="'.$row['id'].'" class="cm-confirm delcomment">Удалить</a></li>
                            </ul>
                        </td>
                    </tr>';
            }
        ?>
    </table>
    
    <div class="table-tools">
        <a class="check_all" href="javascript:void(0);">Выбрать все</a>| 
        <a class="uncheck_all" href="javascript:void(0);">Снять выделение со всех</a>
    </div>
    <span class="submit-button cm-button-main" style="margin-top:15px;">
		<input type="submit" class="del_comments" value="Удалить комментарии">
	</span>
</div>