<div class="cm-notification-container"></div>
<?=$vars['message']?>
<div>
	<div class="clear mainbox-title-container">
		<h1 class="mainbox-title">Новый модуль:&nbsp;</h1>
	</div>
	<div class="extra-tools">
		
	</div>
	<div class="mainbox-body"> 
		<div class="cm-tabs-content">
			<form class="cm-form-highlight cm-check-changes" name="page_update_form" method="post" action="">
				<div id="content_basic" style="display: block;">
					<fieldset>
						<h2 class="subheader"> Информация </h2>
                        <div class="form-field">
                            <label class="cm-required" for="page">Название:</label>
                            <input type="text" class="input-text-large main-input" value="" size="55" name="name" id="name_module" />
                        </div>
                        <div class="form-field">
                            <label class="cm-required" for="page">Таблицы:</label>
                            <input type="text" class="input-text-large main-input" value="" size="55" name="tables" id="tables_module" />
                        </div>
                        <div class="form-field">
                            <label for="page_meta_keywords">Описание:</label>
                            <textarea class="input-textarea-long" rows="2" cols="55" name="comment" id="comment_module"></textarea>
                        </div>
                        <div class="form-field">
                            <label for="page">Подключаемый модуль:</label>
                            <select name="module" id="add_module">
                                <option value="">Выберите модуль...</option>
                                <?php
                                    foreach($vars['dir'] as $row)
                                    {
                                        $active=0;
                                        foreach($vars['list']['list'] as $row2)
                                        {
                                            if($row==$row2['controller'])$active=1;
                                        }
                                        if($active==0)echo "<option value='$row'>$row</option>";
                                    }
                                ?>
                            </select>
                        </div>
						
                        <div class="form-field">
                            <label for="page_meta_keywords">Описание:</label>
                            <select name="sub">
                                <option value="">Выберите раздел...</option>
                                <?php
                                foreach($vars['menu'] as $row)
                                {
                                    echo'<option value="'.$row['id'].'">'.$row['name'].'</option>';
                                }
                                ?>
                            </select>
                        </div>
						<div class="form-field">
                            <label for="page_meta_keywords">Создать папку для файлов:</label>
                            <input type="checkbox" name="create_dir" />
                        </div>
					</fieldset>
                    <fieldset>
                        <h2 class="subheader"> Права доступа </h2>
                        <table width="50%" cellspacing="0" cellpadding="0" border="0" class="table table-fixed hidden-inputs tb_sort" id="photos" style="margin-top: 0;">
                            <tr>
                                <th>Название модуля</th>
                                <th style="text-align:center;" width="80">Чтение</th>
                                <th style="text-align:center;" width="140">Изменение/Удаление</th>
                                <th style="text-align:center;" width="80">Добавление</th>
                            </tr>
                            <?php
                            //echo count($_POST['read']).'<br />'.count($_POST['del']).'<br />'.count($_POST['add']).'<br />';
                            foreach($vars['modules'] as $row)
                            {
                                echo'<tr>
                                        <td>'.$row['name'].'<input type="hidden" value="'.$row['id'].'" name="module_id[]" /></td>
                                        <td style="text-align:center;"><input type="checkbox" value="'.$row['id'].'" name="read'.$row['id'].'" id="read'.$row['id'].'" class="read_chmod" /></td>
                                        <td style="text-align:center;"><input type="checkbox" value="'.$row['id'].'" name="del'.$row['id'].'" id="del'.$row['id'].'" class="del_chmod" /></td>
                                        <td style="text-align:center;"><input type="checkbox" value="'.$row['id'].'" name="add'.$row['id'].'" id="add'.$row['id'].'" class="add_chmod" /></td>
                                    </tr>';
                            }
                            echo'<tr>
                                        <td></td>
                                        <td style="text-align:center;"><input type="checkbox" value="" id="read_all" /></td>
                                        <td style="text-align:center;"><input type="checkbox" value="" id="del_all" /></td>
                                        <td style="text-align:center;"><input type="checkbox" value="" id="add_all" /></td>
                                    </tr>';
                            ?>
                        </table>
                    </fieldset>
				</div>
				<div class="buttons-container cm-toggle-button buttons-bg">
					<div class="cm-buttons-floating hidden" style="display: block;">
						<div class="cm-buttons-placeholder">
							<span class="submit-button cm-button-main">
								<input type="submit" value="Создать" name="add" />
							</span>&nbsp;
							<span class="submit-button cm-button-main cm-save-and-close">
								<input type="submit" value="Создать и закрыть" name="add_close" class="cm-save-and-close" />
							</span> &nbsp;или&nbsp;&nbsp; 
							<a class="underlined tool-link" href="/admin/menu">Отменить</a>
						</div>
					</div>
				</div>
				<input type="hidden" value="<?=$vars['action']?>" id="action" />
			</form>
		</div>
	</div>
</div>