<?
	if(isset($vars['menu'])&&count($vars['menu'])!=0)
	{
?>
<div class="cm-j-tabs" id="navigation">
	<ul>
		<li<? if(!isset($vars['sub']))echo' class="cm-active"';?>><span><a href="/admin/<?=$vars['action']?>"><?=$vars['name']?></a></span></li>
		<?
            foreach($vars['menu'] as $row)
			{
            	$class='';
            	if(isset($vars['sub'])&&$vars['sub']==$row['name'])$class=' class="cm-active"';
            	echo'<li'.$class.'><span><a href="'.$row['url'].'">'.$row['title'].'</a></span></li>';	
            }
        ?>
	</ul>
</div>
<?
	}
?>