<link href="/tpl/admin/css/jquery.Jcrop.css" rel="stylesheet" type="text/css" />
<link href="/tpl/admin/css/fileuploader.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/tpl/admin/js/upload_image.js"></script>
<script type="text/javascript" src="/tpl/admin/js/jquery.Jcrop.min.js"></script>
<script type="text/javascript" charset="utf-8">  
	$("#loading_ac").ajaxStart(function(){$(this).show();});
	$("#loading_ac").ajaxStop(function(){$(this).hide();});
</script>
<div class="error" style="color:red;"></div>

<?
	if(!isset($_SESSION['type_upload']))$_SESSION['type_upload']=1;
?>
<table style="margin-bottom:10px;">
    <tr>
    	<td style="padding-right:35px;" valign="top">
        	<div id="thumb1" style="margin-top:10px;">
				<?
                    $photo = '';
                    if(isset($vars['edit']['photo']))
                    {
                        echo'<img class="bord_img" src="/'.$vars['edit']['photo'].'" />
                             <input type="hidden" id="current_photo" name="current_photo" value="'.$vars['edit']['photo'].'" />';
                    }
                    else{
                        echo'<img class="bord_img" src="" />
                             <input type="hidden" value="" id="current_photo" name="current_photo" />';	
                    }
                ?>
                
                <?
                    if(isset($vars['edit']['photo']))
                    {
                        echo'<br /><a href="'.$vars['edit']['photo'].'" dir="thumb1" class="del_image" id="bord_img_del"';
                        if(!file_exists($vars['edit']['photo']))echo' style="display:none;"';echo'>Удалить</a>';
                    }
                ?>
            </div>
            
            
            
           

        </td>
        <td style="padding-right:35px;" valign="top">
        	<h3>Выберите вариант загрузки изображений</h3>
        	<div style="margin-bottom:25px; text-align:left;" id="display_image_type">
                
                <input type="radio" id="image_crop1" name="image_upload_type" value="1" <? if($_SESSION['type_upload']==1)echo'checked="checked"';?> />
                <label for="image_crop1" style="margin:0; padding:3px; width:auto; float:none;">Вырезать рабочую область</label><br />
                
                
                <input type="radio" id="image_crop2" name="image_upload_type" value="2" <? if($_SESSION['type_upload']==2)echo'checked="checked"';?> />
                <label for="image_crop2" style="margin:0; padding:3px; width:auto; float:none;">Подогнать под размер</label><br />
                
                
                <input type="radio" id="image_crop3" name="image_upload_type" value="3" <? if($_SESSION['type_upload']==3)echo'checked="checked"';?> />
                <label for="image_crop3" style="margin:0; padding:3px; width:auto; float:none;">Загрузить оригинал</label>
            </div>
			
            
        	
             <table id="tb_size"<? if($_SESSION['type_upload']==3)echo'style="display:none;"';?>>
                <tr><td colspan="2"><h3>Размеры миниатюры</h3></td></tr>
                <tr><td>Ширина:</td><td> <input type="text" id="width_image" value="<?=$vars['width']?>" style="width:30px;" /> px</td></tr>
                <tr><td>Высота:</td><td> <input type="text" id="height_image" value="<?=$vars['height']?>" style="width:30px;" /> px</td></tr>
            </table>
            
            <h3>Источник</h3>
            <table id="tb_size">
                <tr>
                <td>Файл с локального компьютера: </td>
                <td>
                	<input type="text" style="width:202px; border:1px solid #ccc; padding: 2px 5px;" id="" name="" disabled="disabled" value="jpg, jpeg, gif, bmp, png" />
                    <input type="file" style="width:220px;" id="image_file" name="image_file" /></td></tr>
                <tr>
                	<td align="right">Ссылка на изображение (url): </td>
                	<td><input type="text" id="load_url_image" value="" style="width:210px;" /> <input type="button" value="Загрузить" id="load_url_image_submit" ></td>
                </tr>
            </table>
            
            
        </td>
    </tr>
</table>
<div>
    <div id="image_div" style="display:none;">
        <img src="" id="load_img" /><br />
    </div>
    
    <div style="display:table-cell;">
        <div id="cut_avatar" style="display: none; display:table-cell;">
            <input type="hidden" name="x" id="x" />
            <input type="hidden" name="y" id="y" />
            <input type="hidden" name="w" id="w" />
            <input type="hidden" name="h" id="h" />
            <input type="hidden" name="src" id="src" />
            
            <input type="hidden" value="<?=$vars['path']?>" id="path_image" />
            <input type="hidden" name="resize_photo_id" id="resize_photo_id" value="<?=$vars['image_id']?>" />
            
            <?
                if(isset($vars['width2']))echo'<input type="hidden" id="width_image2" value="'.$vars['width2'].'" />';
                if(isset($vars['height2']))echo'<input type="hidden" id="height_image2" value="'.$vars['height2'].'" />';
            ?>
            <span id="thumb" style="display: none;"></span>
        </div>
        
        <div id="create_t" style="display:none; margin:10px 0 40px 0; float:right;">
            <input type="button" value=" Вырезать " onclick="javascript:createAvatar('');" id="create" class="button" />
        </div>
    </div>
</div>