<div class="cm-notification-container"></div>
<?=$vars['message']?>
<div>
	<div class="clear mainbox-title-container">
		<h1 class="mainbox-title">Новая страница:&nbsp;</h1>
	</div>
	<div class="extra-tools">
		
	</div>
	<div class="mainbox-body"> 
		<div class="cm-tabs-content">
			<form class="cm-form-highlight cm-check-changes" name="page_update_form" method="post" action="" enctype="multipart/form-data">
				<input type="hidden" value="<?=$vars['edit']['id']?>" name="id" />
				<div id="content_basic" style="display: block;">
                    <fieldset>
                        <h2 class="subheader"> Личные данные  </h2>
                        <div class="form-field">
                            <label for="page" class="cm-required">Пользователь:</label>
                            <input type="text" class="input-text" value="" size="32" name="username" />
                        </div>
                       

                        <div class="form-field">
                            <label for="page">Адрес:</label>
                            <input type="text" class="input-text" value="" size="32" name="address" />
                        </div>
						
						<div class="form-field">
                            <label for="page">Телефон:</label>
                            <input type="text" class="input-text" value="" size="32" name="phone" />
                        </div>
						<div class="form-field">
							<label for="page">E-mail:</label>
                            <input type="text" class="input-text" value="" size="32" name="email" />
						</div>
						<div class="form-field">
                            <label for="page">Почтовый индекс:</label>
                            <input type="text" class="input-text" value="" size="32" name="post_index" />
                        </div>
  
                        <div class="form-field">
                            <label for="page">Страна:</label>
                            <input type="text" class="input-text" value="" size="32" name="country" />
                        </div>
						<div class="form-field">
                            <label for="page">Город:</label>
                            <input type="text" class="input-text" value="" size="32" name="city" />
                        </div>
						<?php
							if(isset($vars['delivery'])&&count($vars['delivery'])!=0)
							{
								echo'<div class="form-field">
										<label for="page">Способ доставки:</label>
										<select name="delivery">';
									
								echo'<option value="0">Выберите вариант доставки</option>';
								foreach($vars['delivery'] as $row)
								{
									$price='';
									if($row['price']!=0.00)
									{
										$price = Numeric::viewPrice($row['price']);
										$price=" +".$price['price'];
									}
									echo'<option value="'.$row['id'].'">'.$row['name'].' '.$price.'</option>';
								}
								echo'</select>
								</div>';
							}
							
							if(isset($vars['payment'])&&count($vars['payment'])!=0)
							{
								echo'<div class="form-field">
										<label for="page">Способ оплаты:</label>
										<select name="payment">';
									
								echo'<option value="0">Выберите вариант оплаты</option>';
								foreach($vars['payment'] as $row)
								{
									echo'<option value="'.$row['id'].'">'.$row['name'].'</option>';
								}
								echo'</select>
								</div>';
							}
						?>
						 <div class="form-field">
                            <label for="page_page_title">Комментарии к заказу:</label>
                            <textarea class="input-textarea" rows="10" cols="30" name="comment"></textarea>
                        </div>
                    </fieldset>
				</div>
				<div class="buttons-container cm-toggle-button buttons-bg">
					<div class="cm-buttons-floating hidden" style="display: block;">
						<div class="cm-buttons-placeholder">
							<span class="submit-button cm-button-main">
								<input type="submit" value="Создать" name="add" />
							</span>&nbsp;
							<span class="submit-button cm-button-main cm-save-and-close">
								<input type="submit" value="Создать и закрыть" name="add_close" class="cm-save-and-close" />
							</span> &nbsp;или&nbsp;&nbsp; 
							<a class="underlined tool-link" href="/admin/<?=$vars['action']?>">Отменить</a>
						</div>
					</div>
				</div>
				<input type="hidden" value="<?=$vars['action']?>" id="action" />
			</form>
		</div>
	</div>
</div>