<div class="items-container multi-level">
<table width="100%" cellspacing="0" cellpadding="0" border="0" class="table table-fixed hidden-inputs tb_sort">
	<tr>
		<th width="20" class="center"><input type="checkbox" class="check_all2" title="Отметить/снять все" value="Y" name="check_all"></th>
		<th width="30">ID</th>
        <th width="120">Дата заказа</th>
		<th>Пользователь</th>
        <th>E-mail</th>
		<th width="100">Сумма (<?=$vars['currency']['icon']?>)</th>
		<th width="70">Статус</th>
        <th width="50">XML</th>
		<th width="170" style="text-align:center;">Действие</th>
	</tr>
	<?php
		foreach($vars['list']['list'] as $row)
		{
			echo'<tr>
					<td class="center"><input type="checkbox" class="check-item" value="'.$row['id'].'" name="id[]" /></td>
					<td><span>'.$row['id'].'</span></td>
					<td><span>'.Date::date_view($row['date_add'], "dd/mm/YY, hh:ii").'</span></td>
					<td>'.$row['username'].'</td>
					<td><a href="mailto:'.$row['email'].'" class="tool-link">'.$row['email'].'</a></td>
					<td>'.$row['sum'].'</td>
					<td>'.$row['status'].'</td>
					<td>'.(file_exists('files/orders/'.$row['id'].'.xml')?'<a href="/download.php?type=orders&file='.$row['id'].'.xml">скачать</a>':'-').'</td>
					<td>
						<a href="/admin/'.$vars['action'].'/edit/'.$row['id'].'" class="tool-link">Редактировать</a>
						&nbsp;&nbsp;|		
						<ul class="cm-tools-list tools-list">
							<li><a href="/admin/'.$vars['action'].'/delete/'.$row['id'].'" class="cm-confirm">Удалить</a></li>
						</ul>
					</td>
				</tr>';
		}
	?>
</table>
</div>
<div class="table-tools">
	<a class="check_all" href="javascript:void(0);">Выбрать все</a>| 
	<a class="uncheck_all" href="javascript:void(0);">Снять выделение со всех</a>
</div>
<? echo $vars['list']['paging']?>