<fieldset>
<h2 class="subheader"> Экспорт </h2>
<table>
	<tr>
    	<td style="width:200px;">ID</td>
        <td>
        	<select name="export_id">
            	<option value="" style="color:#666666;">Пусто</option>
                <option value="A" selected="selected">A</option>
                <option value="B">B</option>
                <option value="C">C</option>
                <option value="D">D</option>
                <option value="E">E</option>
                <option value="F">F</option>
                <option value="G">G</option>
                <option value="H">H</option>
                <option value="I">I</option>
                <option value="J">J</option>
                <option value="K">K</option>
                <option value="L">L</option>
            </select>
        </td>
    </tr>
    <tr>
    	<td>Название</td>
        <td>
        	<select name="export_name">
				<option value="" style="color:#666666;">Пусто</option>
             	<option value="A">A</option>
                <option value="B" selected="selected">B</option>
                <option value="C">C</option>
                <option value="D">D</option>
                <option value="E">E</option>
                <option value="F">F</option>
                <option value="G">G</option>
                <option value="H">H</option>
                <option value="I">I</option>
                <option value="J">J</option>
                <option value="K">K</option>
                <option value="L">L</option>
            </select>
        </td>
    </tr>
    <tr>
    	<td>Краткое описание</td>
        <td>
        	<select name="export_body_m">
				<option value="" style="color:#666666;">Пусто</option>
            	 <option value="A">A</option>
                <option value="B">B</option>
                <option value="C" selected="selected">C</option>
                <option value="D">D</option>
                <option value="E">E</option>
                <option value="F">F</option>
                <option value="G">G</option>
                <option value="H">H</option>
                <option value="I">I</option>
                <option value="J">J</option>
                <option value="K">K</option>
                <option value="L">L</option>
            </select>
        </td>
    </tr>
    <tr>
    	<td>Описание</td>
        <td>
        	<select name="export_body">
				<option value="" style="color:#666666;">Пусто</option>
             	<option value="A">A</option>
                <option value="B">B</option>
                <option value="C">C</option>
                <option value="D" selected="selected">D</option>
                <option value="E">E</option>
                <option value="F">F</option>
                <option value="G">G</option>
                <option value="H">H</option>
                <option value="I">I</option>
                <option value="J">J</option>
                <option value="K">K</option>
                <option value="L">L</option>
            </select>
        </td>
    </tr>
    <tr>
    	<td>Артикул</td>
        <td>
        	<select name="export_code">
				<option value="" style="color:#666666;">Пусто</option>
             	<option value="A">A</option>
                <option value="B">B</option>
                <option value="C">C</option>
                <option value="D">D</option>
                <option value="E" selected="selected">E</option>
                <option value="F">F</option>
                <option value="G">G</option>
                <option value="H">H</option>
                <option value="I">I</option>
                <option value="J">J</option>
                <option value="K">K</option>
                <option value="L">L</option>
            </select>
        </td>
    </tr>
    <tr>
    	<td>Изображение большое</td>
        <td>
        	<select name="export_image">
				<option value="" style="color:#666666;">Пусто</option>
            	<option value="A">A</option>
                <option value="B">B</option>
                <option value="C">C</option>
                <option value="D">D</option>
                <option value="E">E</option>
                <option value="F" selected="selected">F</option>
                <option value="G">G</option>
                <option value="H">H</option>
                <option value="I">I</option>
                <option value="J">J</option>
                <option value="K">K</option>
                <option value="L">L</option>
            </select>
        </td>
    </tr>
    <tr>
    	<td>Цена</td>
        <td>
        	<select name="export_price">
				<option value="" style="color:#666666;">Пусто</option>
             	<option value="A">A</option>
                <option value="B">B</option>
                <option value="C">C</option>
                <option value="D">D</option>
                <option value="E">E</option>
                <option value="F">F</option>
                <option value="G" selected="selected">G</option>
                <option value="H">H</option>
                <option value="I">I</option>
                <option value="J">J</option>
                <option value="K">K</option>
                <option value="L">L</option>
            </select>
        </td>
    </tr>
    <tr>
    	<td>В наличии</td>
        <td>
        	<select name="export_stock">
				<option value="" style="color:#666666;">Пусто</option>
             	<option value="A">A</option>
                <option value="B">B</option>
                <option value="C">C</option>
                <option value="D">D</option>
                <option value="E">E</option>
                <option value="F">F</option>
                <option value="G">G</option>
                <option value="H" selected="selected">H</option>
                <option value="I">I</option>
                <option value="J">J</option>
                <option value="K">K</option>
                <option value="L">L</option>
            </select>
        </td>
    </tr>
    <tr>
    	<td>ID категории</td>
        <td>
        	<select name="export_catalog_id">
				<option value="" style="color:#666666;">Пусто</option>
            <option value="A">A</option>
                <option value="B">B</option>
                <option value="C">C</option>
                <option value="D">D</option>
                <option value="E">E</option>
                <option value="F">F</option>
                <option value="G">G</option>
                <option value="H">H</option>
                <option value="I" selected="selected">I</option>
                <option value="J">J</option>
                <option value="K">K</option>
                <option value="L">L</option>
            </select>
        </td>
    </tr>
    
    <tr>
    	<td>Название категории</td>
        <td>
        	<select name="export_cat_name">
				<option value="" style="color:#666666;">Пусто</option>
            	<option value="A">A</option>
                <option value="B">B</option>
                <option value="C">C</option>
                <option value="D">D</option>
                <option value="E">E</option>
                <option value="F">F</option>
                <option value="G">G</option>
                <option value="H">H</option>
                <option value="I">I</option>
                <option value="J" selected="selected">J</option>
                <option value="K">K</option>
                <option value="L">L</option>
            </select>
        </td>
    </tr>
</table>
</fieldset>    