<div class="items-container multi-level">
<table width="100%" cellspacing="0" cellpadding="0" border="0" class="table table-fixed hidden-inputs tb_sort">
	<tr>
		<th width="170">Дата изменения</th>
		<th>Название</th>
		<th width="100" style="text-align:center;">Действие</th>
	</tr>
	<?php
		foreach($vars['list'] as $row)
		{
			$url=str_replace('/', '--', $row['path']);
			$url=str_replace('.', '---', $url);
			$url=str_replace('css', 'css2', $url);
			echo'<tr>
					<td><span>'.$row['time'].'</span></td>
					<td><span>'.$row['path'].'</span></td>
					<td>
						<a href="/admin/'.$vars['action'].'/edit/'.$url.'" class="tool-link">Редактировать</a>
					</td>
				</tr>';
		}
	?>
</table>
</div>