<div class="cm-notification-container"></div>
<?=$vars['message']?>
<div>
	<div class="clear mainbox-title-container">
		<h1 class="mainbox-title">Водяной знак</h1>
	</div>
	<div class="mainbox-body"> 
		<div class="cm-tabs-content">
			<form class="cm-form-highlight cm-check-changes" method="post" enctype="multipart/form-data">
				<div id="content_basic" style="display: block;">
					<fieldset>
						<h2 class="subheader"> Настройки водяного знака: </h2>
                        <div class="form-field">
							<label class="cm-required">Статус:</label>
							<div class="select-field">
								<input type="radio" class="radio" value="1" id="page_data_0_a" name="active" <? if($vars['edit']['active']==1)echo' checked="checked"';?>>
								<label for="page_data_0_a">Вкл.</label>
								<input type="radio" class="radio" value="0" id="page_data_0_d" name="active" <? if($vars['edit']['active']==0)echo' checked="checked"';?>>
								<label for="page_data_0_d">Выкл.</label>
							</div>
						</div>
                        <div class="form-field">
							<label class="cm-required">Тип изображение, куда нужно наносить знак:</label>
							<div class="select-field">
								<input type="radio" class="radio" value="0" id="type_image1" name="type_image" <? if($vars['edit']['type_image']==0)echo' checked="checked"';?>>
								<label for="type_image1">Только миниатюру</label>
                                
								<input type="radio" class="radio" value="1" id="type_image2" name="type_image" <? if($vars['edit']['type_image']==1)echo' checked="checked"';?>>
								<label for="type_image2">Только на большую</label>
                                
                                <input type="radio" class="radio" value="2" id="type_image3" name="type_image" <? if($vars['edit']['type_image']==2)echo' checked="checked"';?>>
								<label for="type_image3">На все картинки</label>
							</div>
						</div>
                        <div class="form-field">
							<label class="cm-required">Модули, где нужно наносить знак:</label>
							<div class="select-field">
								<?
									foreach($vars['modules'] as $row)
									{
										$checked='';
										foreach($vars['edit']['modules'] as $row2)
										{
											if($row['controller']==$row2)
											{
												$checked=' checked="checked"';
												break;
											}
										}
										
										echo'<div>
												<input type="checkbox" value="'.$row['controller'].'" name="modules[]" id="mod'.$row['id'].'" '.$checked.' />
											 	<label for="mod'.$row['id'].'">'.$row['name'].'</label>
											 </div>';	
									}
								?>
							</div>
						</div>
                        <div class="form-field">
							<label class="cm-required">Тип:</label>
							<div class="select-field">
								<input type="radio" class="radio" value="1" id="watermark_type1" name="watermark_type" <? if($vars['edit']['type']==1)echo' checked="checked"';?>>
								<label for="watermark_type1">Картинка</label>
                                <input type="radio" class="radio" value="0" id="watermark_type0" name="watermark_type" <? if($vars['edit']['type']==0)echo' checked="checked"';?>>
								<label for="watermark_type0">Текст</label>
							</div>
						</div>
                        <div class="form-field">
                            <label for="watermark_position">Позиция: </label>
                            <input type="hidden" name="watermark_position" value="<?=$vars['edit']['position']?>" />
                            <div class="pos_block<? if($vars['edit']['position']=='top_left')echo' hov_position';?>" id="top_left" title="В левом верхнем углу"><div></div></div>
                            <div class="pos_block<? if($vars['edit']['position']=='top_center')echo' hov_position';?>" id="top_center" title="По центру сверху"><div></div></div>
                            <div class="pos_block<? if($vars['edit']['position']=='top_right')echo' hov_position';?>" id="top_right" title="В правом верхнем углу"><div></div></div>
                            <div class="clear"></div>
                            <div class="pos_block<? if($vars['edit']['position']=='center_left')echo' hov_position';?>" id="center_left" title="Слева по центру"><div></div></div>
                            <div class="pos_block<? if($vars['edit']['position']=='center_center')echo' hov_position';?>" id="center_center" title="По центру"><div></div></div>
                            <div class="pos_block<? if($vars['edit']['position']=='center_right')echo' hov_position';?>" id="center_right" title="Справа по центру"><div></div></div>
                            <div class="clear"></div>
                            <div class="pos_block<? if($vars['edit']['position']=='bot_left')echo' hov_position';?>" id="bot_left" title="В левом нижнем углу"><div></div></div>
                            <div class="pos_block<? if($vars['edit']['position']=='bot_center')echo' hov_position';?>" id="bot_center" title="По центру снизу"><div></div></div>
                            <div class="pos_block<? if($vars['edit']['position']=='bot_right')echo' hov_position';?>" id="bot_right" title="В правом нижнем углу"><div></div></div>
                            <div class="clear"></div>
                        </div>
						<div class="type_watermark_div" id="text_image_watermark"<? if($vars['edit']['type']==0)echo' style="display:block;"';?>>
                            <div class="form-field">
                                <label for="watermark_text">Текст: </label>
                                <input class="input-text-large main-input" id="watermark_text" style="width:400px;" type="text" name="watermark_text" value="<?=$vars['edit']['text']?>" />
                            </div>
                            <div class="form-field">
                                <label for="watermark_font_size">Размер текст: </label>
                                <select name="watermark_font_size" id="watermark_font_size">
                                    <?
                                        for($i=10;$i<=64;$i++)
                                        {
                                            echo'<option value="'.$i.'"';if($vars['edit']['font_size']==$i)echo' selected';echo'>'.$i.'</option>';	
                                        }
                                    ?>
                                </select>
                            </div>
                            <div class="form-field">
                                <label for="watermark_width">Ширина: </label>
                                <input type="text" id="watermark_width" name="watermark_width" value="<?=$vars['edit']['width']?>" style="width:50px;" /> px
                            </div>
                            <div class="form-field">
                                <label for="watermark_width">Высота: </label>
                                <input type="text" id="watermark_height" name="watermark_height" value="<?=$vars['edit']['height']?>" style="width:50px;" /> px
                            </div>
                            <div class="form-field">
                                <label for="watermark_top">Отступ сверху: </label>
                                <input type="text" id="watermark_top" name="watermark_top" value="<?=$vars['edit']['top']?>" style="width:50px;" /> px
                            </div>
                            <div class="form-field">
                                <label for="watermark_left">Отступ слева: </label>
                                <input type="text" id="watermark_left" name="watermark_left" value="<?=$vars['edit']['left']?>" style="width:50px;" /> px
                            </div>
                            <div class="form-field">
                                <label for="colorpickerField1">Цвет текста: </label>
                                <input type="text" value="<?=$vars['edit']['font_color']?>" name="watermark_font_color" id="colorpickerField1" style="width:55px; margin-right:5px;" />
                                <span id="cur_color" style="padding: 2px 10px 1px 10px; border: 1px solid #000; background-color: #<?=$vars['edit']['font_color'];?>;"></span>
                            </div>
                            <div class="form-field">
                                <label for="colorpickerField2">Цвет фона: </label>
                                <input type="text" value="<?=$vars['edit']['back_color']?>" name="watermark_back_color" id="colorpickerField2" style="width:55px; margin-right:5px;" />
                                <span id="cur_color" style="padding: 2px 10px 1px 10px; border: 1px solid #000; background-color: #<?=$vars['edit']['back_color'];?>;"></span>
                            </div>
                            <div class="form-field">
                                <label for="watermark_opacity_font">Прозрачность текста: </label>
                                <select name="watermark_opacity_font" id="watermark_opacity_font">
                                <?
                                    for($i=0;$i<=100;$i+=5)
                                    {
                                        echo'<option value="'.$i.'"';if($vars['edit']['opacity_font']==$i)echo' selected';echo'>'.$i.'</option>';	
                                    }
                                ?>
                                </select>
                            </div>
                            <div class="form-field">
                                <label for="watermark_opacity_back">Прозрачность фона: </label>
                                <select name="watermark_opacity_back" id="watermark_opacity_back">
                                <?
                                    for($i=0;$i<=100;$i+=10)
                                    {
                                        echo'<option value="'.$i.'"';if($vars['edit']['opacity_back']==$i)echo' selected';echo'>'.$i.'</option>';	
                                    }
                                ?>
                                </select>
                            </div>
                         </div>
                         <div class="type_watermark_div" id="image_watermark"<? if($vars['edit']['type']==1)echo' style="display:block;"';?>>
                             <div class="form-field">
                                <label for="watermark_file">Выберите водяной знак: </label>
                                <input type="file" name="watermark_file" id="watermark_file" />
                                <input type="hidden" name="watermark_file_current" value="<?=$vars['edit']['image']?>" />
                             </div>
                         </div>
                         <div class="form-field">
                            <?
                                if(file_exists($vars['edit']['image']))echo'<div style="margin-top:10px;"><img src="/'.$vars['edit']['image'].'" /></div>';
                            ?>
                         </div>
					</fieldset>
				</div>
				<div class="buttons-container cm-toggle-button buttons-bg">
					<div class="cm-buttons-floating hidden" style="display: block;">
						<div class="cm-buttons-placeholder">
							<span class="submit-button cm-button-main">
								<input type="submit" value="Сохранить" name="update" />
							</span>
						</div>
					</div>
				</div>
				<input type="hidden" value="<?=$vars['action']?>" id="action" />
			</form>
		</div>
	</div>
</div>