<div class="block_title"><?=$vars['translate']['catalog']?></div>
<div id="left_menu">
	<ul>
		<?
			//if(!isset($vars['open_link']['level_1']))$vars['open_link']['level_1']=9;
			$vars['open_link']['level_1']=9;
            foreach($vars['menu'] as $row)
            {
				if($row['sub']==$vars['open_link']['level_1'])
				{
					$pos = strpos($row['url'], "http://");
					if($pos !== false)$link=$row['url'].'" target="_blank" rel="nofollow';
					else $link="/catalog/".$row['url'];
					echo'<li><a href="'.$link.'">'.$row['name'].'</a>';
					
					/*if(isset($vars['open_link']['level_1'])&&$row['id']==$vars['open_link']['level_1'])
					{
						$sub='';
						foreach($vars['menu'] as $row2)
						{
							if($row2['sub']==$row['id'])
							{
								$pos = strpos($row2['url'], "http://");
								if($pos !== false)$link=$row2['url'].'" target="_blank" rel="nofollow';
								else $link="/catalog/".$row2['url'];
								
								if(isset($vars['cur_product'])&&$vars['cur_product']==$row2['id'])$class='class="cur_product"';
								else $class='';
								$sub.='<li '.$class.'><a href="'.$link.'">'.$row2['name'].'</a></li>';	
							}
							
						}
						if($sub!='')echo'<ul>'.$sub.'</ul>';
					}*/
					echo'</li>';
				}
            }
        ?>
	</ul>
</div>