<h2 align="center"><?=$vars['translate']['my_orders']?></h2>
<?
	if(!isset($vars['order']))
	{
?>
	<table width="100%" class="orders" cellpadding="0" cellspacing="0">
    	<tr>
            <th width="90">ID заказа</th>
            <th>Статус</th>
            <th>Дата</th>
            <th>Сумма</th>
        </tr>
        <?
			$i=0;
			foreach($vars['orders'] as $row)
			{

				echo"<tr>
						<td style='padding:5px 15px;'><a href='/users/orders/id/{$row['id']}'>#{$row['id']}</a></td>
						<td>{$row['name']}</td>
						<td>".$this->date_view($row['date_add'], "dd/mm/YY, hh:ii")."</td>
						<td>{$row['sum']}</td>
					</tr>";
				$i++;	
			}
		?>
    </table>
<?
	}
	else{
		if($vars['order']['id'])
		{
		?>
        <h3>Товары: </h3>
         <table width="100%" class="orders" cellpadding="0" cellspacing="0">
         <tr>
                <th>Название</th>
				<th>Кол-во</th>
				<th>Цена</th>
                <th>Сумма</th>
			</tr>
        <?
			$i=0;
			$summa2=0;
			foreach($vars['product'] as $row)
			{
				$price = viewPrice($row['sum'], $_SESSION['currency'], $row['discount']);
				$summa = viewPrice($price[3]*$row['amount'], 0, 0);
				$summa2+=$row['sum']*$row['amount'];

				echo"<tr>
						<td align='center'>{$row['name']}</td>
						<td align='center'>{$row['amount']}</td>
						<td align='center'>{$price[1]}{$price[0]}</td>
						<td align='center'>{$summa[0]}</td>
					</tr>";
				$i++;	
			}
			$summa = viewPrice($vars['order']['sum'], $_SESSION['currency'], 0);
		?>
        </table>
        <table align="right" style="margin-top:5px;">
		<tr><td style="border-right:1px dotted #ccc; height:20px; padding-right:5px;">Сумма: </td><td style="padding-left:5px;"><?=$vars['order']['sum']?></td></tr></table><br />
        <br />
        <div style="margin:0 auto;">
        <h3 align="center">Дополнительная информация: </h3>
         <table width="100%" cellpadding="5">     
           <tr>
              <td align="right" style="font-weight:bold;">ID Заказа: </td>
              <td>#<?=$vars['order']['id']?></td>
           </tr>
           <tr>
              <td align="right" style="font-weight:bold;">Дата заказа: </td>
              <td><?=$vars['order']['date_add']?></td>
           </tr>
           <tr>
              <td align="right" style="font-weight:bold;">Статус: </td>
              <td><?=$vars['order']['name']?></td>
           </tr>
		   <?
		   		if($vars['order']['discount']!="")
				echo'<tr>
					  <td align="right" style="font-weight:bold;">Скидка: </td>
					  <td>'.$vars['order']['discount'].'%</td>
				   </tr>';
				   
				if($vars['order']['country']!="")
				echo'<tr>
					  <td align="right" style="font-weight:bold;">Страна: </td>
					  <td>'.$vars['order']['country'].'</td>
				   </tr>';
				   
				if($vars['order']['city']!="")
				echo'<tr>
					  <td align="right" style="font-weight:bold;">Город: </td>
					  <td>'.$vars['order']['city'].'</td>
				   </tr>';   
				
				if($vars['order']['delivery']!="")
				echo'<tr>
					  <td align="right" style="font-weight:bold;">Способ доставки: </td>
					  <td>'.$vars['order']['delivery'].'</td>
				   </tr>';         
		   ?>
           <tr>
              <td align="center" colspan="2"><?=htmlspecialchars_decode($vars['order']['comment'])?></td>
           </tr>
        </table> 
       </div>
        <?
	}
	else echo"<div class='err'>Заказа не существует!</div>";
}
?>