<?
	$dir=createDir($row['id']);
	if(file_exists($dir[0]."{$row['id']}_s.jpg"))$src="/".$dir[0]."{$row['id']}_s.jpg";
	else $src="/files/default.jpg";
	
	$price=viewPrice($row['price'], $row['discount']);

/*	if($row['discount']!=0)
	{
		$discount="<div class='discount'>{$row['discount']}%</div>";
		$price=viewPrice($row['price'], $_SESSION['currency'], $row['discount']);
	}
	else $discount='';*/
	
	if($row['status_id']==1)$status='<span class="status">Акция</span>';
	else $status='';

	if($i==2)
	{
		$i=-1;
		$style=' style="margin-right:0;"';
	}
	else $style='';
?>
    <div class="product" <?=$style?>>
		<div class="photo_product">
			<a title="<?=$row['name']?>" href="/product/<?=$row['url']?>">
				<img alt="<?=$row['name']?>" title="<?=$row['name']?>" src="<?=$src?>" /><br />
			</a>
		</div>		
		<div class="info_product">
			<div class="name_product"><a title="<?=$row['name']?>" href="/product/<?=$row['url']?>"><?=$row['name']?></a></div>
			<?=$status?>
			<div class="price"><?=$price['price']?></div>
			<button class="buy" name="<?=$row['id']?>" type="button">Купить!</button>
		</div>	
	</div>