<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
        <title><?php echo $vars['meta']['title'];?></title>
		<meta name="keywords" content="<?php echo $vars['meta']['keywords']; ?>" />
		<meta name="description" content="<?php echo $vars['meta']['description']; ?>" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="copyright" content="" />
		<meta name="Author-Corporate" content="" />
		<meta name="Publisher-Email" content="" />
        <?=$vars['webmaster']?>
		<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
        <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
        <?php echo $vars['styles']; ?>
        <!--[if lte IE 7]>
            <?php echo $this->LoadResource('styles', 'style_ie.css'); ?>
        <![endif]-->
        <?php echo $vars['scripts']; //?>
        <?php
			if(isset($vars['google']))
			echo"<script type=\"text/javascript\">
				  var _gaq = _gaq || [];
				  _gaq.push(['_setAccount', '".$vars['google']."']);
				  _gaq.push(['_trackPageview']);
				
				  (function() {
					var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
					ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
					var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
				  })();
				</script>";
		?>
	</head>
<body>
<div id="wrapper">
    <div id="head">
        <div id="banner"></div>
    </div>
	<div id="header">
        <div class="holder">
            <div id="logo"><a href="<?=LINK?>/"><img src="<?=IMAGES?>logo.png" alt="" /></a></div>
            <?php echo $vars['menu'];?>
            <div id="login">
               <?
                    if(!isset($_SESSION['user_id']))
                    {
                        ?>
                        <a href="javascript:void(0);" onclick="showLogin();" class="enter"> <?=$vars['translate']['enter']?></a> <span>или</span>
                        <a href="javascript:void(0);" onclick="showRegister();" class="reg"><?=$vars['translate']['sign_up3']?></a>
                        <?
                    }
                    else
                    {
                        echo '<a href="javascript:void(0);" class="enter"><b>'.$_SESSION['email'].'</b></a>
                    <a href="/'.$vars['lang'].'/users/logout" class="reg">'.$vars['translate']['exit'].'</a>';
                    }
                ?>
            </div>
        </div>
	</div>
    <div class="holder">
        <div id="head_menu">
                <div id="logo_big">
                      <a href="/"><img src="<?=IMAGES?>logo_big.png" alt="" /></a>
                </div>
                <? echo htmlspecialchars_decode($vars['top_block']['body']);?>
                <div id="phones">
                    <? echo htmlspecialchars_decode($vars['phones']['body']);?>
                </div>
                <div id="bascket">
                </div>
        </div>
        <?php echo $vars['cat_menu'];?>
        <div class="search-bar">
            <div class="search">
                <div id="results_search"></div>
                <form action="/catalog/all" method="get" autocomplete="off">
                    <input type="text" id="live-search-input" name="search" placeholder="Введите название товара или артикул ..." value="<? if(isset($_GET['search'])) echo $_GET['search'];?>" >
                    <button type="submit">Найти</button>
                </form>
            </div>
            <a class="button leave-message" href="/contacts"><img src="<?=IMAGES?>cloud.png">Оставить сообщение</a>
            <a class="link" href="<?=LINK?>/catalog/novetly">Новинки магазина</a>
        </div>

        <div id="content">
            <? if(isset($vars['breadcrumbs']))echo $vars['breadcrumbs'];?>
            <?=$vars['content'];?>
            <? if(isset($vars['meta']['text']))echo'<div class="bot_text">'.htmlspecialchars_decode($vars['meta']['text']).'</div>';?>
            <div class="clear"></div>
        </div>

    <div class="subscribe-block">
        <div class="left">
            <? echo htmlspecialchars_decode($vars['block_8']['body']);?>
        </div>
        <form id="subscribe_form">
              <div>
				<label>Ваше имя:</label><br />
              	<input type="text" name="subscribe-name" id="subscribe-name" value="" />
              </div>
              <div>
              	<label>Ваш email:</label><br />
              	<input type="text" name="subscribe-email" id="subscribe-email" value="" />
              </div>
              <input type="submit" value="OK" />
        </form>
        <div class="right">
            <a href="/chto-vas-ozhidaet-v-rassylke-"><span>Что вас ожидает в рассылке?</span></a>
        </div>
    </div>

    </div>
    <div class="footer-fix"></div>
</div>
<div id="footer">
    <div class="holder">
        <div class="exchange-block">
            <div>
                <span class="title">Что делать,
                если не подошло бельё?</span>
                <p>
                    Мы с удовольствием</br>
                    <a href="/">поменяем его</a> >>
                </p>
            </div>
        </div>

        <div class="addr-menu">
            <?=htmlspecialchars_decode($vars['address']['body'])?>
        </div>
            <div class="bot_text">
				<?=htmlspecialchars_decode($vars['footer_text']['body'])?>
            </div>
            <div class="clear"></div>
        </div>
    </div>
</div>
<div id="overlay"></div>
<?php echo htmlspecialchars_decode($vars['testing_mode']); ?>
</body>
</html>